//! Integration tests for the HUGR-to-PHIR parser.
//!
//! Tests load real `.hugr` files generated by Guppy and verify the
//! resulting PHIR Module structure.

#![cfg(feature = "hugr")]

use pecos_engines::quantum::StateVecEngine;
use pecos_engines::{ClassicalEngine, Engine};
use pecos_phir::PhirEngine;
use pecos_phir::builtin_ops::BuiltinOp;
use pecos_phir::hugr_parser::parse_hugr_bytes_to_phir;
use pecos_phir::ops::{ClassicalOp, Operation, QuantumOp};
use std::io::Cursor;
use tket::TketOp;
use tket::extension::rotation::ConstRotation;
use tket::hugr::Hugr;
use tket::hugr::builder::{DFGBuilder, Dataflow, DataflowHugr};
use tket::hugr::envelope::EnvelopeConfig;
use tket::hugr::types::Signature;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Get the entry block of the "main" function inside a `ModuleOp`.
fn get_main_block(module: &pecos_phir::builtin_ops::ModuleOp) -> &pecos_phir::phir::Block {
    let top_block = module
        .body
        .blocks
        .first()
        .expect("module should have a body block");
    let func_instr = top_block
        .operations
        .first()
        .expect("module should contain a function");
    if let Operation::Builtin(BuiltinOp::Func(func)) = &func_instr.operation {
        func.body
            .first()
            .and_then(|r| r.blocks.first())
            .expect("function should have entry block")
    } else {
        panic!(
            "first operation should be a Func, got {:?}",
            func_instr.operation
        );
    }
}

/// Collect operation type names from a block (e.g. "quantum.h", "arith.result").
fn op_names(block: &pecos_phir::phir::Block) -> Vec<String> {
    block
        .operations
        .iter()
        .map(|i| i.operation.name())
        .collect()
}

/// Count occurrences of a specific `QuantumOp` variant in a block.
fn count_quantum_ops<F>(block: &pecos_phir::phir::Block, pred: F) -> usize
where
    F: Fn(&QuantumOp) -> bool,
{
    block
        .operations
        .iter()
        .filter(|i| matches!(&i.operation, Operation::Quantum(q) if pred(q)))
        .count()
}

/// Count `VarDefine` ops in a block.
fn count_var_defines(block: &pecos_phir::phir::Block) -> usize {
    block
        .operations
        .iter()
        .filter(|i| matches!(&i.operation, Operation::Builtin(BuiltinOp::VarDefine(_))))
        .count()
}

/// Check that a block has a Result op with the given `export_name`.
fn has_result_with_export(block: &pecos_phir::phir::Block, name: &str) -> bool {
    block.operations.iter().any(|i| {
        matches!(&i.operation, Operation::Classical(ClassicalOp::Result))
            && i.attributes.get("export_name").and_then(|v| {
                if let pecos_phir::phir::AttributeValue::String(s) = v {
                    Some(s.as_str())
                } else {
                    None
                }
            }) == Some(name)
    })
}

fn crz_hugr(theta: f64, basis: usize) -> Hugr {
    let mut builder = DFGBuilder::new(Signature::new(vec![], vec![])).expect("create HUGR");
    let mut target = builder
        .add_dataflow_op(TketOp::QAlloc, vec![])
        .expect("allocate target")
        .outputs()
        .next()
        .expect("target output");
    let mut control = builder
        .add_dataflow_op(TketOp::QAlloc, vec![])
        .expect("allocate control")
        .outputs()
        .next()
        .expect("control output");

    if basis & 1 != 0 {
        target = builder
            .add_dataflow_op(TketOp::X, vec![target])
            .expect("prepare target")
            .outputs()
            .next()
            .expect("target output");
    }
    if basis & 2 != 0 {
        control = builder
            .add_dataflow_op(TketOp::X, vec![control])
            .expect("prepare control")
            .outputs()
            .next()
            .expect("control output");
    }

    let rotation = builder.add_load_value(
        ConstRotation::new(theta / std::f64::consts::PI).expect("finite HUGR rotation"),
    );
    let mut outputs = builder
        .add_dataflow_op(TketOp::CRz, vec![control, target, rotation])
        .expect("add CRz")
        .outputs();
    control = outputs.next().expect("control output");
    target = outputs.next().expect("target output");
    builder
        .add_dataflow_op(TketOp::QFree, vec![target])
        .expect("free target");
    builder
        .add_dataflow_op(TketOp::QFree, vec![control])
        .expect("free control");
    builder
        .finish_hugr_with_outputs(vec![])
        .expect("finish HUGR")
}

fn hugr_bytes(hugr: &Hugr) -> Vec<u8> {
    let mut buffer = Cursor::new(Vec::new());
    hugr.store(&mut buffer, EnvelopeConfig::text())
        .expect("serialize HUGR");
    buffer.into_inner()
}

fn state_from_phir_hugr_parser(theta: f64, basis: usize) -> Vec<(f64, f64)> {
    let module =
        parse_hugr_bytes_to_phir(&hugr_bytes(&crz_hugr(theta, basis))).expect("parse HUGR to PHIR");
    let mut phir = PhirEngine::new(module).expect("create PHIR engine");
    let mut simulator = StateVecEngine::new(2);
    while !phir.finished {
        let commands = phir.generate_commands().expect("generate PHIR commands");
        simulator.process(commands).expect("execute PHIR commands");
    }
    simulator
        .simulator_mut()
        .state()
        .iter()
        .map(|amplitude| (amplitude.re, amplitude.im))
        .collect()
}

fn assert_crz_matrix(execute: impl Fn(f64, usize) -> Vec<(f64, f64)>) {
    for theta in [
        -std::f64::consts::PI,
        std::f64::consts::PI / 3.0,
        std::f64::consts::PI,
        std::f64::consts::TAU,
        3.0 * std::f64::consts::PI,
    ] {
        let mut actual = vec![vec![(0.0, 0.0); 4]; 4];
        for column in 0..4 {
            for (row_values, amplitude) in actual.iter_mut().zip(execute(theta, column)) {
                row_values[column] = amplitude;
            }
        }

        let half = theta / 2.0;
        let reference = [
            (1.0, 0.0),
            (1.0, 0.0),
            (half.cos(), -half.sin()),
            (half.cos(), half.sin()),
        ];
        let phase = actual[0][0];
        let phase_norm = phase.0 * phase.0 + phase.1 * phase.1;
        assert!(
            (phase_norm - 1.0).abs() < 1e-12,
            "theta={theta}, phase={phase:?}"
        );
        if theta.abs() <= std::f64::consts::PI {
            assert!((phase.0 - 1.0).abs() < 1e-12 && phase.1.abs() < 1e-12);
        } else {
            assert!((phase.0.abs() - 1.0).abs() < 1e-12 && phase.1.abs() < 1e-12);
        }

        for (row, row_values) in actual.iter().enumerate() {
            for (column, &value) in row_values.iter().enumerate() {
                let normalized = (
                    (value.0 * phase.0 + value.1 * phase.1) / phase_norm,
                    (value.1 * phase.0 - value.0 * phase.1) / phase_norm,
                );
                let expected = if row == column {
                    reference[row]
                } else {
                    (0.0, 0.0)
                };
                assert!(
                    (normalized.0 - expected.0).abs() < 1e-12
                        && (normalized.1 - expected.1).abs() < 1e-12,
                    "theta={theta}, entry=({row}, {column}), actual={normalized:?}, expected={expected:?}, phase={phase:?}"
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Real .hugr file tests
// ---------------------------------------------------------------------------

#[test]
fn phir_hugr_crz_boundary_preserves_full_matrix() {
    assert_crz_matrix(state_from_phir_hugr_parser);
}

#[test]
fn parse_single_hadamard_hugr() {
    let bytes = include_bytes!("../../../crates/pecos/tests/test_data/hugr/single_hadamard.hugr");
    let module = parse_hugr_bytes_to_phir(bytes).expect("single_hadamard.hugr should parse");

    assert_eq!(module.name, "hugr_module");

    let block = get_main_block(&module);
    let names = op_names(block);

    // Should have VarDefine for qubits and classical registers
    assert!(
        count_var_defines(block) >= 1,
        "should have VarDefine ops: {names:?}"
    );

    // Should contain an H gate
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::H)) >= 1,
        "should contain at least one H gate: {names:?}"
    );

    // Should contain a Measure
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::Measure)) >= 1,
        "should contain at least one Measure: {names:?}"
    );

    // Should have Result op exporting to "c"
    assert!(
        has_result_with_export(block, "c"),
        "should have Result with export_name 'c': {names:?}"
    );
}

#[test]
fn parse_bell_state_hugr() {
    let bytes = include_bytes!("../../../crates/pecos/tests/test_data/hugr/bell_state.hugr");
    let module = parse_hugr_bytes_to_phir(bytes).expect("bell_state.hugr should parse");

    let block = get_main_block(&module);
    let names = op_names(block);

    // Bell state: H on qubit 0, CX on (0, 1), measure both
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::H)) >= 1,
        "Bell state should have H: {names:?}"
    );
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::CX)) >= 1,
        "Bell state should have CX: {names:?}"
    );
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::Measure)) >= 2,
        "Bell state should measure 2 qubits: {names:?}"
    );
}

#[test]
fn parse_ghz_state_hugr() {
    let bytes = include_bytes!("../../../crates/pecos/tests/test_data/hugr/ghz_state.hugr");
    let module = parse_hugr_bytes_to_phir(bytes).expect("ghz_state.hugr should parse");

    let block = get_main_block(&module);
    let names = op_names(block);

    // GHZ: H on qubit 0, CX on (0,1), CX on (1,2), measure all 3
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::H)) >= 1,
        "GHZ should have H: {names:?}"
    );
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::CX)) >= 2,
        "GHZ should have >= 2 CX gates: {names:?}"
    );
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::Measure)) >= 3,
        "GHZ should measure 3 qubits: {names:?}"
    );
}

#[test]
fn parse_rz_x_hugr() {
    let bytes = include_bytes!("../../../crates/pecos/tests/test_data/hugr/rz_x.hugr");
    let module = parse_hugr_bytes_to_phir(bytes).expect("rz_x.hugr should parse");

    let block = get_main_block(&module);
    let names = op_names(block);

    // Explicit Rz(pi) retains its symmetric rotation matrix rather than
    // becoming the phase-sensitive named Z gate.
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::RZ(_))) >= 1,
        "Rz(pi) should remain RZ: {names:?}"
    );

    // Should contain an X gate
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::X)) >= 1,
        "should contain X gate: {names:?}"
    );

    // Should have measurements
    assert!(
        count_quantum_ops(block, |q| matches!(q, QuantumOp::Measure)) >= 2,
        "should measure 2 qubits: {names:?}"
    );
}

// ---------------------------------------------------------------------------
// Error handling tests
// ---------------------------------------------------------------------------

#[test]
fn parse_empty_input_errors() {
    let result = parse_hugr_bytes_to_phir(&[]);
    assert!(result.is_err(), "empty input should error");
}

#[test]
fn parse_garbage_input_errors() {
    let result = parse_hugr_bytes_to_phir(b"not a hugr file at all");
    assert!(result.is_err(), "garbage input should error");
}

#[test]
fn parse_nested_control_flow_errors() {
    for (name, bytes) in [
        (
            "conditional",
            include_bytes!("../../../crates/pecos/tests/test_data/hugr/conditional_x.hugr")
                as &[u8],
        ),
        (
            "tail loop",
            include_bytes!("../../../crates/pecos/tests/test_data/hugr/simple_while_loop.hugr")
                as &[u8],
        ),
    ] {
        let result = parse_hugr_bytes_to_phir(bytes);
        assert!(
            result.is_err(),
            "{name} HUGR must not silently drop nested operations"
        );
    }
}

// ---------------------------------------------------------------------------
// Structural tests
// ---------------------------------------------------------------------------

#[test]
fn single_hadamard_var_defines_correct() {
    let bytes = include_bytes!("../../../crates/pecos/tests/test_data/hugr/single_hadamard.hugr");
    let module = parse_hugr_bytes_to_phir(bytes).expect("parse");

    let block = get_main_block(&module);

    // Collect VarDefine details
    let var_defs: Vec<(&str, &str, usize)> = block
        .operations
        .iter()
        .filter_map(|i| {
            if let Operation::Builtin(BuiltinOp::VarDefine(v)) = &i.operation {
                Some((v.name.as_str(), v.var_type.as_str(), v.size))
            } else {
                None
            }
        })
        .collect();

    // Should have at least a qubit register
    assert!(
        var_defs.iter().any(|(_, t, _)| *t == "qubits"),
        "should have qubit VarDefine: {var_defs:?}"
    );

    // If there are measurements, should have classical registers too
    let has_measure = block
        .operations
        .iter()
        .any(|i| matches!(&i.operation, Operation::Quantum(QuantumOp::Measure)));
    if has_measure {
        assert!(
            var_defs.iter().any(|(n, t, _)| *n == "c" && *t == "i64"),
            "measured circuit should have 'c' classical register: {var_defs:?}"
        );
    }
}

#[test]
fn bell_state_no_alloc_ops() {
    // VarDefine handles allocation; there should be no explicit Alloc instructions
    let bytes = include_bytes!("../../../crates/pecos/tests/test_data/hugr/bell_state.hugr");
    let module = parse_hugr_bytes_to_phir(bytes).expect("parse");

    let block = get_main_block(&module);
    let alloc_count = count_quantum_ops(block, |q| matches!(q, QuantumOp::Alloc));
    assert_eq!(
        alloc_count, 0,
        "should have no Alloc ops (VarDefine handles allocation)"
    );
}

#[test]
fn bell_state_measurement_bit_packing() {
    // Verify that measurements produce the Bitcast + Shl + Or pattern
    let bytes = include_bytes!("../../../crates/pecos/tests/test_data/hugr/bell_state.hugr");
    let module = parse_hugr_bytes_to_phir(bytes).expect("parse");

    let block = get_main_block(&module);
    let names = op_names(block);

    // Should have Bitcast, Shl, Or for bit packing
    assert!(
        names.iter().any(|n| n == "arith.bitcast"),
        "should have Bitcast for bit packing: {names:?}"
    );
    assert!(
        names.iter().any(|n| n == "arith.shl"),
        "should have Shl for bit packing: {names:?}"
    );
    assert!(
        names.iter().any(|n| n == "arith.or"),
        "should have Or for bit packing: {names:?}"
    );
}
