//! Auto-generated Rust tests from experimental/composable-noise.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


// Simple: just set error rates

#[test]
fn test_experimental_composable_noise_rust_1() {
    use pecos_neo::noise::prelude::*;
    let model = depolarizing_with_measurement(0.001, 0.01, 0.02);

    // Or use the builder for more control
    let model = NoiseModelBuilder::new()
        .with_depolarizing(0.001, 0.01)
        .with_measurement_error(0.02)
        .build();
}


// Simple depolarizing noise

#[test]
fn test_experimental_composable_noise_rust_2() {
    use pecos_neo::noise::prelude::*;
    let model = depolarizing_only(0.001, 0.01);

    // With measurement errors
    let model = depolarizing_with_measurement(0.001, 0.01, 0.02);

    // Realistic device noise with all parameters
    let model = realistic_device_noise(
        &DeviceNoiseParams::new()
            .with_p1(0.001)
            .with_p2(0.01)
            .with_measurement_error(0.02)
            .with_t1(0.0001)
    );

    // Surface code optimized noise
    let model = surface_code_noise(0.001, true);
}



#[test]
fn test_experimental_composable_noise_rust_3() {
    use pecos_neo::noise::prelude::*;
    let model = NoiseModelBuilder::new()
        .with_depolarizing(0.001, 0.01)
        .with_measurement_error(0.02)
        .with_preparation_error(0.001)
        .with_idle_noise(0.0001, 0.0005)  // T1 and T2 rates
        .build();
}


// Custom single-qubit noise with leakage handling

#[test]
fn test_experimental_composable_noise_rust_4() {
    use pecos_neo::noise::prelude::*;
    let sq_noise = seq![
        skip_if_leaked(),                    // Skip gate if qubit is leaked
        prob(0.001,                          // 0.1% error probability
            when_leaked(
                seep(),                      // Leaked: return to computational basis
                sample![
                    (0.1, leak()),           // 10% of errors cause leakage
                    (0.9, pauli()),          // 90% are Pauli errors
                ]
            )
        ),
    ];

    let model = NoiseModelBuilder::new()
        .with_single_qubit_noise(sq_noise)
        .build();
}


// Using pattern

#[test]
fn test_experimental_composable_noise_rust_5() {
    use pecos_neo::noise::prelude::*;
    let model = depolarizing_only(0.001, 0.01);

    // Using primitives
    let sq = CompositeChannelBuilder::single_qubit("sq", prob(0.001, pauli()));
    let tq = CompositeChannelBuilder::two_qubit("tq", prob(0.01, pauli()));
}


// Symmetric (same error rate for 0->1 and 1->0)

#[test]
fn test_experimental_composable_noise_rust_6() {
    use pecos_neo::noise::prelude::*;
    let model = measurement_only(0.02, 0.02);

    // Asymmetric
    let model = measurement_only(0.01, 0.03);  // p(0->1)=1%, p(1->0)=3%

    // Using primitives for outcome-dependent noise
    let meas_noise = seq![
        on_zero(prob(0.01, flip_outcome())),  // 1% flip when measuring 0
        on_one(prob(0.03, flip_outcome())),   // 3% flip when measuring 1
    ];
}



#[test]
fn test_experimental_composable_noise_rust_7() {
    use pecos_neo::noise::prelude::*;
    let model = with_leakage(
        0.001,  // p1: single-qubit error rate
        0.01,   // p2: two-qubit error rate
        0.1,    // 10% of errors cause leakage
        0.5,    // 50% seepage rate (return from leaked state)
    );
}


// Using builder

#[test]
fn test_experimental_composable_noise_rust_8() {
    use pecos_neo::noise::prelude::*;
    let model = NoiseModelBuilder::new()
        .with_idle_noise(0.0001, 0.0005)  // T1 rate, T2 rate
        .build();

    // Using primitives for custom idle behavior
    let t1 = CompositeChannelBuilder::idle("t1", prob_linear(0.0001, pauli()));
    let t2 = CompositeChannelBuilder::idle("t2", prob_linear(0.0005, inject_z()));
}


// 1D chain crosstalk during measurement

#[test]
fn test_experimental_composable_noise_rust_9() {
    use pecos_neo::noise::prelude::*;
    let model = chain_measurement_crosstalk(0.01);

    // 2D grid crosstalk (5 columns)
    let model = grid_measurement_crosstalk(5, 0.01);

    // Custom crosstalk with composite primitives
    let crosstalk = CompositeCrosstalkChannel::new("custom", prob(0.01, inject_z()))
        .responds_to_measurement()
        .local(chain_neighbors);  // Only affect adjacent qubits
}


// Chain-correlated errors

#[test]
fn test_experimental_composable_noise_rust_10() {
    use pecos_neo::noise::prelude::*;
    let model = chain_correlated(0.01, 0.5);  // 50% correlation factor

    // Using CorrelatedNoiseChannel directly
    let channel = CorrelatedNoiseChannel::new(0.01, 0.5);
}


// Neighbor functions for crosstalk

#[test]
fn test_experimental_composable_noise_rust_11() {
    use pecos_neo::noise::prelude::*;
    use pecos_neo::prelude::QubitId;
    let _neighbors = chain_neighbors;      // 1D: qubit i neighbors i-1, i+1
    let _neighbors = grid_neighbors(5);    // 2D grid with 5 columns

    // Distance functions for correlation decay
    let (a, b) = (QubitId(0), QubitId(3));
    let _d = chain_distance(a, b);       // |i - j|
    let _d = grid_distance(5)(a, b);     // Manhattan distance on grid

    // Decay functions for distance-weighted correlations
    let decay = exponential_decay(0.5, 2.0);  // 0.5 * exp(-d/2)
    let decay = gaussian_decay(1.0, 3.0);     // exp(-(d/3)^2)
    let decay = power_law_decay(1.0, 2.0);    // 1/(1+d)^2
}
