//! Auto-generated Rust tests from README.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_readme_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    // Define a Bell state circuit
    let circuit = Qasm::from_string(r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#);

    // Run 10 shots
    let results = sim(circuit).seed(42).run(10)?;
    println!("{:?}", results);
    // 0 = both |0⟩, 3 = both |1⟩ (always correlated!)
    Ok(())
}

