//! Auto-generated Rust tests from user-guide/decoders.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_decoders_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

// Create a parity check matrix in COO (coordinate) format
let rows: Vec<u32> = vec![0, 0, 1, 1];
let cols: Vec<u32> = vec![0, 1, 2, 3];
let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

// Build decoder with configuration
let mut decoder = BpOsdDecoder::builder(&pcm)
    .error_rate(error_rate)
    .max_iter(100)
    .bp_method(BpMethod::MinimumSum)
    .osd_method(OsdMethod::OsdE)
    .osd_order(10)
    .build()?;

// Decode syndrome
let result = decoder.decode(&syndrome.view())?;

println!("Decoding: {:?}", result.decoding);
println!("Converged: {}", result.converged);
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_3() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = BpLsdDecoder::builder(&pcm)
    .error_rate(error_rate)
    .bits_per_step(1)
    .lsd_order(10)
    .build()?;

let result = decoder.decode(&syndrome.view())?;
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_4() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = BeliefFindDecoder::builder(&pcm)
    .error_rate(error_rate)
    .uf_method(UfMethod::Inversion)
    .max_iter(10)
    .build()?;

let result = decoder.decode(&syndrome.view())?;
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_5() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = FlipDecoder::builder(&pcm)
    .max_iter(100)
    .build()?;

let result = decoder.decode(&syndrome.view())?;
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_6() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = UnionFindDecoder::builder(&pcm)
    .method(UfMethod::Inversion)
    .build()?;

// Union find decode takes syndrome, LLRs, and bits_per_step
let llrs = vec![0.1; 4];  // one LLR per bit column
let result = decoder.decode(&syndrome.view(), &llrs, 1)?;
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_7() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = SoftInfoBpDecoder::builder(&pcm)
    .error_rate(error_rate)
    .max_iter(50)
    .build()?;

// Soft decode takes soft syndrome values, cutoff, and sigma
let soft_syndrome = vec![0.9, 0.1];
let result = decoder.decode(&soft_syndrome, 5.0, 0.5)?;
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_8() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = BpOsdDecoder::builder(&pcm).error_rate(error_rate).build()?;

let syndromes = vec![
    array![1u8, 0],
    array![0u8, 1],
];

for (i, syn) in syndromes.iter().enumerate() {
    let result = decoder.decode(&syn.view())?;
    println!("Syndrome {}: {:?}", i, result.decoding);
}
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_9() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = BpOsdDecoder::builder(&pcm)
    .error_rate(error_rate)
    .bp_schedule(BpSchedule::Parallel)
    .omp_threads(4)
    .build()?;
    Ok(())
}


#[test]
fn test_user_guide_decoders_rust_10() -> Result<(), Box<dyn std::error::Error>> {
    use ndarray::array;
    use pecos_decoders::{BeliefFindDecoder, BpLsdDecoder, BpMethod, BpOsdDecoder, BpSchedule, Decoder, FlipDecoder, InputVectorType, LdpcError, OsdMethod, SoftInfoBpDecoder, SparseMatrix, UfMethod, UnionFindDecoder};
    let rows: Vec<u32> = vec![0, 0, 1, 1];
    let cols: Vec<u32> = vec![0, 1, 2, 3];
    let pcm = SparseMatrix::from_coo(2, 4, rows, cols)?;
    let error_rate = 0.05;
    let syndrome = array![1u8, 0];

let mut decoder = BpOsdDecoder::builder(&pcm).error_rate(error_rate).build()?;

match decoder.decode(&syndrome.view()) {
    Ok(result) => {
        println!("Decoding: {:?}", result.decoding);
        println!("Converged: {}", result.converged);
    }
    Err(e) => {
        eprintln!("Decoding error: {}", e);
    }
}
    Ok(())
}
