//! Auto-generated Rust tests from user-guide/getting-started.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py


use pecos::prelude::*;

#[test]
fn test_user_guide_getting_started_rust_1() {
    let sim = SparseStab::new(1);
    println!("PECOS is working! Created a {}-qubit simulator", sim.num_qubits());
}
    

use pecos_hugr::hugr_sim;

#[test]
fn test_user_guide_getting_started_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    // Load and run a pre-compiled repetition code circuit
    let results = hugr_sim("repetition_code.hugr")
        .seed(42)
        .run(10)?;

    // View results
    for shot in &results.shots {
        println!("Syndrome: {:?}", shot.data);
    }
    Ok(())
}
    
