//! Auto-generated Rust tests from user-guide/engine-selection.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


// Compile-time engine selection - best performance

#[test]
fn test_user_guide_engine_selection_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_engines::sim;
    use pecos_programs::Qasm;
    use pecos_qasm::qasm_engine;
    let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[1];
    creg c[1];
    h q[0];
    measure q[0] -> c[0];
    "#;
    let results = sim(qasm_engine().program(Qasm::from_string(qasm_code)))
        .seed(42)
        .run(10)?;

    // Verify results
    assert_eq!(results.len(), 10);
    let shot_map = results.try_as_shot_map().unwrap();
    let values = shot_map.try_bits_as_u64("c").unwrap();
    // H gate creates superposition, so we should see both 0 and 1
    assert!(values.iter().any(|&v| v == 0) || values.iter().any(|&v| v == 1));
    Ok(())
}


// Runtime engine selection based on user input

#[test]
fn test_user_guide_engine_selection_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::{DynamicEngineBuilder, EngineType, sim_dynamic};
    use pecos_programs::Qasm;
    use pecos_qasm::qasm_engine;
    let user_input = "qasm";
    let engine_type = match user_input {
        "qasm" => EngineType::Qasm,
        "llvm" => EngineType::Llvm,
        "selene" => EngineType::Selene,
        _ => panic!("Unknown engine type"),
    };

    // For this example, we'll just use QASM
    let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[1];
    creg c[1];
    h q[0];
    measure q[0] -> c[0];
    "#;
    let builder = DynamicEngineBuilder::new(qasm_engine().program(Qasm::from_string(qasm_code)));

    // Use the same API regardless of engine type
    let results = sim_dynamic(builder).seed(42).run(10)?;
    assert_eq!(results.len(), 10);
    Ok(())
}
