//! Auto-generated Rust tests from user-guide/gates.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_gates_rust_2() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);

let mut sim = SparseStab::new(5);
let q = QubitId(0);
let (q0, q1) = (QubitId(0), QubitId(1));

}


#[test]
fn test_user_guide_gates_rust_3() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.identity(&[q]);

}


#[test]
fn test_user_guide_gates_rust_4() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.x(&[q]);

}


#[test]
fn test_user_guide_gates_rust_5() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.y(&[q]);

}


#[test]
fn test_user_guide_gates_rust_6() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.z(&[q]);

}


#[test]
fn test_user_guide_gates_rust_7() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.h(&[q]);

}


#[test]
fn test_user_guide_gates_rust_8() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.h2(&[q]);  // H2 variant
sim.h3(&[q]);  // H3 variant
sim.h4(&[q]);  // H4 variant
sim.h5(&[q]);  // H5 variant
sim.h6(&[q]);  // H6 variant

}


#[test]
fn test_user_guide_gates_rust_9() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.sx(&[q]);
sim.sxdg(&[q]);  // Adjoint (inverse)

}


#[test]
fn test_user_guide_gates_rust_10() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.sy(&[q]);
sim.sydg(&[q]);  // Adjoint (inverse)

}


#[test]
fn test_user_guide_gates_rust_11() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.sz(&[q]);
sim.szdg(&[q]);  // Adjoint (inverse): [[1, 0], [0, -i]]

}


#[test]
fn test_user_guide_gates_rust_12() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.f(&[q]);
sim.fdg(&[q]);  // Adjoint: X→Z, Y→X, Z→Y

}


#[test]
fn test_user_guide_gates_rust_13() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.f2(&[q]);   sim.f2dg(&[q]);
sim.f3(&[q]);   sim.f3dg(&[q]);
sim.f4(&[q]);   sim.f4dg(&[q]);

}


#[test]
fn test_user_guide_gates_rust_14() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.cx(&[control, target]);

}


#[test]
fn test_user_guide_gates_rust_15() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.cy(&[control, target]);

}


#[test]
fn test_user_guide_gates_rust_16() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.cz(&[q1, q2]);

}


#[test]
fn test_user_guide_gates_rust_17() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.swap(&[q1, q2]);

}


#[test]
fn test_user_guide_gates_rust_18() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.iswap(&[q1, q2]);

}


#[test]
fn test_user_guide_gates_rust_19() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.sxx(&[q1, q2]);
sim.sxxdg(&[q1, q2]);  // Adjoint

}


#[test]
fn test_user_guide_gates_rust_20() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.syy(&[q1, q2]);
sim.syydg(&[q1, q2]);  // Adjoint

}


#[test]
fn test_user_guide_gates_rust_21() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.szz(&[q1, q2]);
sim.szzdg(&[q1, q2]);  // Adjoint

}


#[test]
fn test_user_guide_gates_rust_22() {
    use pecos::prelude::*;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let mut sim = SparseStab::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let control = QubitId(0);
    let target = QubitId(1);
    sim.g(&[q1, q2]);

}


#[test]
fn test_user_guide_gates_rust_23() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);

let mut sim = StateVec::new(5);
let q = QubitId(0);
let (q0, q1) = (QubitId(0), QubitId(1));
let theta = Angle64::from_radians(PI / 4.0);

}


#[test]
fn test_user_guide_gates_rust_24() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.rx(theta, &[q]);

}


#[test]
fn test_user_guide_gates_rust_25() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.ry(theta, &[q]);

}


#[test]
fn test_user_guide_gates_rust_26() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.rz(theta, &[q]);

}


#[test]
fn test_user_guide_gates_rust_27() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.t(&[q]);
sim.tdg(&[q]);  // Adjoint (T†)

}


#[test]
fn test_user_guide_gates_rust_28() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.u(theta, phi, lam, &[q]);

}


#[test]
fn test_user_guide_gates_rust_29() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.r1xy(theta, phi, &[q]);

}


#[test]
fn test_user_guide_gates_rust_30() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.rxx(theta, &[q1, q2]);

}


#[test]
fn test_user_guide_gates_rust_31() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.ryy(theta, &[q1, q2]);

}


#[test]
fn test_user_guide_gates_rust_32() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.rzz(theta, &[q1, q2]);

}


#[test]
fn test_user_guide_gates_rust_33() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    let results = sim.mz(&[q]);
// results[0].outcome: true if |1⟩, false if |0⟩
// results[0].is_deterministic: true if already in eigenstate

}


#[test]
fn test_user_guide_gates_rust_34() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    let results = sim.mx(&[q]);   // Measure +X
let results = sim.mnx(&[q]);  // Measure -X

}


#[test]
fn test_user_guide_gates_rust_35() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    let results = sim.my(&[q]);   // Measure +Y
let results = sim.mny(&[q]);  // Measure -Y

}


#[test]
fn test_user_guide_gates_rust_36() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.pz(&[q]);   // Prepare |0⟩ (eigenstate of +Z)
sim.pnz(&[q]);  // Prepare |1⟩ (eigenstate of -Z)

}


#[test]
fn test_user_guide_gates_rust_37() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.px(&[q]);   // Prepare |+⟩ = (|0⟩ + |1⟩)/√2
sim.pnx(&[q]);  // Prepare |-⟩ = (|0⟩ - |1⟩)/√2

}


#[test]
fn test_user_guide_gates_rust_38() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.py(&[q]);   // Prepare |+i⟩ = (|0⟩ + i|1⟩)/√2
sim.pny(&[q]);  // Prepare |-i⟩ = (|0⟩ - i|1⟩)/√2

}


#[test]
fn test_user_guide_gates_rust_39() {
    use pecos::prelude::*;
    use pecos::simulators::{ArbitraryRotationGateable, CliffordGateable, StateVec};
    use std::f64::consts::PI;
    let mut sim = StateVec::new(5);
    let q = QubitId(0);
    let q0 = QubitId(0);
    let q1 = QubitId(1);
    let q2 = QubitId(2);
    let theta = Angle64::from_radians(PI / 4.0);
    let phi = Angle64::from_radians(PI / 8.0);
    let lam = Angle64::from_radians(PI / 6.0);
    sim.mpz(&[q]);   // Measure Z, prepare |0⟩
sim.mpnz(&[q]);  // Measure -Z, prepare |1⟩
sim.mpx(&[q]);   // Measure X, prepare |+⟩
sim.mpnx(&[q]);  // Measure -X, prepare |-⟩
sim.mpy(&[q]);   // Measure Y, prepare |+i⟩
sim.mpny(&[q]);  // Measure -Y, prepare |-i⟩

}
