//! Auto-generated Rust tests from user-guide/gate-angle-types.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]



#[test]
fn test_user_guide_gate_angle_types_rust_1() {
    use pecos_core::{Phase, Sign};
    let plus = Sign::PlusOne;
    let minus = Sign::MinusOne;

    // Multiplication is XOR (extremely fast)
    assert_eq!(plus.multiply(&minus), Sign::MinusOne);
    assert_eq!(minus.multiply(&minus), Sign::PlusOne);
}



#[test]
fn test_user_guide_gate_angle_types_rust_2() {
    use pecos_core::{Phase, QuarterPhase};
    let phase = QuarterPhase::PlusI;
    assert!(!phase.is_real());

    // Multiplication
    assert_eq!(QuarterPhase::PlusI.multiply(&QuarterPhase::PlusI), QuarterPhase::MinusOne);

    // Conjugation
    assert_eq!(QuarterPhase::PlusI.conjugate(), QuarterPhase::MinusI);
}


// Quarter phases stored exactly

#[test]
fn test_user_guide_gate_angle_types_rust_3() {
    use pecos_core::Angle64;
    use pecos_core::phase::GlobalPhase;
    let p = GlobalPhase::i();
    assert_eq!(p.as_quarter(), Some(pecos_core::QuarterPhase::PlusI));

    // Arbitrary phase
    let p = GlobalPhase::from_angle(Angle64::from_turns(0.125)); // e^{i*pi/4}
}


// Named constants

#[test]
fn test_user_guide_gate_angle_types_rust_4() {
    use pecos_core::Angle64;
    let zero = Angle64::ZERO;              // 0
    let quarter = Angle64::QUARTER_TURN;   // pi/2
    let half = Angle64::HALF_TURN;         // pi
    let full = Angle64::FULL_TURN;         // 2*pi (wraps to 0)

    // From turns (fractional rotations)
    let eighth = Angle64::from_turns(0.125);  // pi/4

    // Exact rational construction
    let third = Angle64::from_turn_ratio(1, 3);  // 2*pi/3

    // Arithmetic (wrapping modular)
    assert_eq!(quarter + quarter, half);
    assert_eq!(half + half, zero);  // wraps around

    // Conversion to radians (for interop)
    let radians: f64 = quarter.to_radians();
}


// angle! -- pi-based syntax

#[test]
fn test_user_guide_gate_angle_types_rust_5() {
    use pecos_core::{angle, turn};
    let a = angle!(pi);         // pi (half turn)
    let a = angle!(pi / 2);    // pi/2 (quarter turn)
    let a = angle!(pi / 4);    // pi/4 (T gate angle)
    let a = angle!(2 * pi / 3); // 2*pi/3

    // turn! -- turn-based syntax (often more intuitive)
    let a = turn!(1 / 8);  // 1/8 turn = pi/4 (T gate)
    let a = turn!(1 / 4);  // 1/4 turn = pi/2 (S gate)
    let a = turn!(1 / 2);  // 1/2 turn = pi (Z gate)
}


// Global phase applied to a gate

#[test]
fn test_user_guide_gate_angle_types_rust_6() {
    use pecos_core::{phase, phase_turn};
    use pecos_core::unitary::X;
    let op = phase!(pi / 4) * X(0);      // e^{i*pi/4} * X
    let op = phase_turn!(1 / 8) * X(0);  // same thing
}



#[test]
fn test_user_guide_gate_angle_types_rust_7() {
    use pecos_core::prelude::GateType;
    let gate = GateType::CX;
    assert_eq!(gate.quantum_arity(), 2);  // two-qubit gate
    assert!(!gate.is_parameterized());    // no angle parameter
    assert!(gate.is_two_qubit());

    let gate = GateType::RZ;
    assert_eq!(gate.angle_arity(), 1);    // one angle parameter
    assert!(gate.is_parameterized());

    // String parsing (case-insensitive, with aliases)
    let gate: GateType = "CNOT".parse().unwrap();  // alias for CX
    let gate: GateType = "H".parse().unwrap();
}



#[test]
fn test_user_guide_gate_angle_types_rust_8() {
    use pecos_core::{Angle64, AngleSource, GateDefinitionBuilder, GateRegistry};
    use pecos_core::prelude::GateType;
    let mut registry = GateRegistry::new();

    // Define a custom "RZX" gate that decomposes to H-CX-RZ-CX-H
    let def = GateDefinitionBuilder::new("RZX", 2)
        .angle_arity(1)
        .step(GateType::H, &[1])                              // H on target
        .step(GateType::CX, &[0, 1])                          // CX
        .step_with_angles(GateType::RZ, &[1], &[AngleSource::Input(0)])  // RZ(theta)
        .step(GateType::CX, &[0, 1])                          // CX
        .step(GateType::H, &[1])                              // H on target
        .build();
    registry.register(def);

    assert!(registry.contains("RZX"));
}
