//! Auto-generated Rust tests from user-guide/selene-runtime-execution.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_selene_runtime_execution_rust_1() {
    use pecos_qis::{RuntimeNativeGate, RuntimeNativeGateSet, SeleneRuntime};
    let runtime = SeleneRuntime::new("libcustom_runtime.so").with_native_gate_set(
        RuntimeNativeGateSet::new([RuntimeNativeGate::Rxy, RuntimeNativeGate::Rz, RuntimeNativeGate::Rzz]),
    );
}
