//! Auto-generated Rust tests from user-guide/getting-started.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_getting_started_rust_1() {
    use pecos::prelude::*;
    let sim = SparseStab::new(1);
    println!("PECOS is working! Created a {}-qubit simulator", sim.num_qubits());
}



#[test]
fn test_user_guide_getting_started_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;

let program = Qasm::from_string(r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg d[3];
    qreg s[2];
    creg syndrome[2];
    creg data[3];
    cx d[0], s[0];
    cx d[1], s[0];
    cx d[1], s[1];
    cx d[2], s[1];
    measure s -> syndrome;
    measure d -> data;
"#);
let results = sim(program)
    .noise(DepolarizingNoiseModel::builder().with_uniform_probability(0.1))
    .seed(42)
    .shots(10)
    .run()?;

let shot_map = results.try_as_shot_map()?;
println!("Syndromes: {:?}", shot_map.try_bits_as_u64("syndrome")?);

    Ok(())
}

