//! Auto-generated Rust tests from user-guide/hugr-simulation.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py


use pecos_hugr::{hugr_engine, hugr_sim};
use pecos_engines::{ClassicalControlEngineBuilder, ClassicalEngine};

// Load a pre-compiled HUGR file

#[test]
fn test_user_guide_hugr_simulation_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    let results = hugr_sim("bell_state.hugr")
        .seed(42)
        .run(1000)?;

    println!("Results: {:?}", results);
    Ok(())
}

use pecos_hugr::{hugr_engine, hugr_sim};
use pecos_engines::{ClassicalControlEngineBuilder, ClassicalEngine};

// Quick simulation from file

#[test]
fn test_user_guide_hugr_simulation_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    let results = hugr_sim("circuit.hugr")
        .seed(42)
        .run(1000)?;

    // Or use the builder for more control
    let engine = hugr_engine()
        .hugr_file("circuit.hugr")
        .build()?;

    println!("Circuit uses {} qubits", engine.num_qubits());
    Ok(())
}
