//! Auto-generated Rust tests from user-guide/hugr-simulation.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_hugr_simulation_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_engines::{ClassicalControlEngineBuilder, ClassicalEngine};
    use pecos_hugr::{hugr_engine, hugr_sim};
    use std::path::PathBuf;
    let mut hugr_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    hugr_path.push("../../../../../crates/pecos/tests/test_data/hugr/bell_state.hugr");


// Load a pre-compiled HUGR file
let results = hugr_sim(&hugr_path)
    .seed(42)
    .run(1000)?;

println!("Results: {:?}", results);

    Ok(())
}



#[test]
fn test_user_guide_hugr_simulation_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_engines::{ClassicalControlEngineBuilder, ClassicalEngine};
    use pecos_hugr::{hugr_engine, hugr_sim};
    use std::path::PathBuf;
    let mut hugr_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    hugr_path.push("../../../../../crates/pecos/tests/test_data/hugr/bell_state.hugr");


// Quick simulation from file
let results = hugr_sim(&hugr_path)
    .seed(42)
    .run(1000)?;

// Or use the builder for more control
let engine = hugr_engine()
    .hugr_file(&hugr_path)
    .build()?;

println!("Circuit uses {} qubits", engine.num_qubits());

    Ok(())
}

