//! Auto-generated Rust tests from user-guide/pecos-concepts.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]



#[test]
fn test_user_guide_pecos_concepts_rust_1() {
    use pecos_core::pauli::*;
    use pecos_core::PauliOperator;
    let logical_x = X(0) & X(1) & X(2);
    let z_probe = Z(3);

    assert_eq!(logical_x.weight(), 3);
    assert!(logical_x.commutes_with(&z_probe));
}



#[test]
fn test_user_guide_pecos_concepts_rust_2() {
    use pecos_core::{PauliOperator, PauliString};
    let stabilizer: PauliString = "Z0 Z1 Z4 Z5".parse().unwrap();
    assert_eq!(stabilizer.weight(), 4);
}
