//! Auto-generated Rust tests from user-guide/simulators.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_simulators_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);
    // SparseSim is used by default
let results = sim(program.clone()).run(1000)?;

// Or explicitly select it
let results = sim(program)
    .quantum(sparse_stabilizer())
    .run(1000)?;

    Ok(())
}


#[test]
fn test_user_guide_simulators_rust_3() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);
    let results = sim(program)
    .quantum(state_vector())
    .run(100)?;

    Ok(())
}


#[test]
fn test_user_guide_simulators_rust_4() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::QubitId;
    use pecos::simulators::{CliffordGateable, PauliProp};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

// Track how an X error on qubit 0 propagates
let mut prop = PauliProp::new();
prop.add_x(0);  // Track an X error on qubit 0

// Apply Hadamard - transforms X to Z
prop.h(&[QubitId(0)]);

// Check resulting error pattern
assert!(prop.contains_z(0));  // X transformed to Z
assert!(!prop.contains_x(0)); // No longer has X

    Ok(())
}


#[test]
fn test_user_guide_simulators_rust_5() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos_engines::{QuantumEngineBuilder, coin_toss};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

// Test classical logic with random quantum outcomes
// CoinToss ignores all gates and returns random measurements
let mut builder = coin_toss().qubits(2);
let engine = builder.build()?;
// Engine is ready for processing quantum operations

    Ok(())
}


#[test]
fn test_user_guide_simulators_rust_6() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);
    let circuit = Qasm::from_string(r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#);

// Default (sparse stabilizer for Clifford circuits)
let results = sim(circuit.clone()).run(1000)?;

// Explicit simulator selection
let results = sim(circuit.clone())
    .quantum(state_vector())
    .run(1000)?;

let results = sim(circuit)
    .quantum(sparse_stabilizer())
    .run(1000)?;

    Ok(())
}


#[test]
fn test_user_guide_simulators_rust_7() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::QubitId;
    use pecos::simulators::{CliffordGateable, SparseStab};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

// Create simulator with 5 qubits
let mut state = SparseStab::new(5);

// Apply gates
state.h(&[QubitId(0)]);
state.cx(&[QubitId(0), QubitId(1)]);

// Measure
let results = state.mz(&[QubitId(0)]);
println!("Qubit 0 measured: {}", results[0].outcome);

// Inspect stabilizers
println!("{:?}", state);

    Ok(())
}
