//! Auto-generated Rust tests from user-guide/qasm-simulation.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_qasm_simulation_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

// Define the Bell state QASM code
let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

let program = Qasm::from_string(qasm_code);

// Simple simulation
let results = sim(program.clone()).run(1000)?;

// With configuration
let results = sim(program).seed(42).run(1000)?;

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

let program = Qasm::from_string(qasm_code);

// Simple simulation with builder pattern
let results = sim(program.clone()).run(1000)?;

// With more configuration options
let results = sim(program)
    .seed(42)
    .noise(DepolarizingNoiseModel::builder().with_uniform_probability(0.01))
    .workers(4)  // Explicitly set number of threads
    // .auto_workers()  // Or use all available CPU cores
    .run(1000)?;

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_3() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

let program = Qasm::from_string(qasm_code);

let mut experiment = sim(program)
    .seed(42)
    .workers(4)
    .noise(DepolarizingNoiseModel::builder().with_uniform_probability(0.01))
    .build()?;

// Run multiple times
let results_100 = experiment.run(100)?;
let results_1000 = experiment.run(1000)?;

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_4() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

// No noise (ideal simulation)
let _pass = PassThroughNoiseModel::builder();

// Standard depolarizing
let _depol = DepolarizingNoiseModel::builder()
    .with_uniform_probability(0.01);

// Custom depolarizing per operation type
let _custom = DepolarizingNoiseModel::builder()
    .with_prep_probability(0.001)  // State preparation error
    .with_meas_probability(0.002)  // Measurement error
    .with_p1_probability(0.003)    // Single-qubit gate error
    .with_p2_probability(0.004);   // Two-qubit gate error

// Biased depolarizing (asymmetric error distribution)
let _biased = BiasedDepolarizingNoiseModel::builder()
    .with_uniform_probability(0.01);

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_5() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

let noise = GeneralNoiseModelBuilder::new()
    .with_prep_probability(0.001)      // State prep error
    .with_meas_0_probability(0.005)    // Measurement error |0> → |1>
    .with_meas_1_probability(0.01)     // Measurement error |1> → |0>
    .with_p1_probability(0.0001)       // Single-qubit gate error
    .with_p2_probability(0.01)         // Two-qubit gate error
    .with_p_idle_linear_rate(0.0001)     // Idle noise rate
    .with_seed(42);                    // Deterministic noise

// Use with sim()
let results = sim(program).noise(noise).run(1000)?;

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_6() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

let program = Qasm::from_string(qasm_code);

// Sparse stabilizer (default, efficient for Clifford circuits)
let results = sim(program.clone())
    .quantum(sparse_stabilizer())
    .run(1000)?;

// State vector (for non-Clifford circuits)
let results = sim(program)
    .quantum(state_vector())
    .run(1000)?;

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_7() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

let program = Qasm::from_string(qasm_code);
let results = sim(program).run(1000)?;

// Results come as ShotVec
println!("Got {} shots", results.len());

// Convert to ShotMap for columnar access
let shot_map = results.try_as_shot_map()?;

// Access measurement results by register name
let c_values = shot_map.try_bits_as_u64("c")?;
// Returns Vec<u64> where each value is the decimal encoding

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_8() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

fn bell_state_example() -> Result<(), PecosError> {
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;

    let program = Qasm::from_string(qasm_code);

    // Build simulation with depolarizing noise
    let mut experiment = sim(program)
        .seed(42)
        .workers(4)
        .noise(DepolarizingNoiseModel::builder().with_uniform_probability(0.01))
        .build()?;

    // Run multiple times
    for shots in [100, 500, 1000] {
        let results = experiment.run(shots)?;
        println!("Results for {} shots: {:?}", shots, results);
    }

    Ok(())
}

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_9() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

fn ghz_noise_example() -> Result<(), PecosError> {
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[3];
        creg c[3];
        h q[0];
        cx q[0], q[1];
        cx q[1], q[2];
        measure q -> c;
    "#;

    let program = Qasm::from_string(qasm_code);

    // Create advanced noise model with builder
    let noise = GeneralNoiseModelBuilder::new()
        .with_prep_probability(0.001)      // 0.1% state prep error
        .with_p1_probability(0.0001)       // 0.01% single-qubit gate error
        .with_p2_probability(0.01)         // 1% two-qubit gate error
        .with_meas_0_probability(0.02)     // 2% false positive rate
        .with_meas_1_probability(0.03)     // 3% false negative rate
        .with_seed(12345);                 // Deterministic noise

    // Run simulation
    let results = sim(program).noise(noise).seed(42).run(1000)?;
    println!("GHZ state results: {:?}", results);

    Ok(())
}

    Ok(())
}


#[test]
fn test_user_guide_qasm_simulation_rust_10() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use pecos::noise::GeneralNoiseModelBuilder;
    use pecos::simulators::{sparse_stabilizer, state_vector};
    let qasm_code = r#"
        OPENQASM 2.0;
        include "qelib1.inc";
        qreg q[2];
        creg c[2];
        h q[0];
        cx q[0], q[1];
        measure q -> c;
    "#;
    let program = Qasm::from_string(qasm_code);

let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

let program = Qasm::from_string(qasm_code);

// Single threaded (default)
let results = sim(program.clone()).workers(1).run(1000)?;

// Explicit thread count
let results = sim(program.clone()).workers(4).run(1000)?;

// Automatically use all available cores
let results = sim(program).auto_workers().run(1000)?;

    Ok(())
}
