//! Auto-generated Rust tests from user-guide/quantum-operator-algebra.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


// Single-qubit constructors

#[test]
fn test_user_guide_quantum_operator_algebra_rust_1() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    let p = X(0);          // X on qubit 0
    let q = Z(3);          // Z on qubit 3

    // Multi-qubit constructors (same Pauli type on multiple qubits)
    let zz = Zs([0, 1]);          // Z(0) & Z(1)
    let xxx = Xs([0, 1, 2]);      // X(0) & X(1) & X(2)
    let yy = Ys(0..2);            // also accepts ranges

    // Mixed Paulis via tensor product (&)
    let xz = X(0) & Z(1);         // X on qubit 0, Z on qubit 1
    let xzzx = X(0) & Z(1) & Z(2) & X(3);

    // Pauli multiplication (*)
    let xy = X(0) * Z(0);         // X * Z = -iY (same qubit)
    let tensor = X(0) * Z(1);     // different qubits -> tensor product

    // Phases
    let neg = -X(0);              // -X
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_2() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::pauli::algebra::i;
    let imag = i * X(0);          // iX
    let neg_imag = -i * Y(1);     // -iY
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_3() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::{PauliOperator, QuarterPhase};
    let a = X(0) & Z(1);
    let b = Z(0) & X(1);

    // Commutation
    // X(0)Z(1) and Z(0)X(1) anticommute on each qubit, but 2 anticommutations = commute
    assert!(a.commutes_with(&b));
    assert!(a.commutes_with(&a));   // self-commutes

    // Weight (number of non-identity sites)
    assert_eq!(a.weight(), 2);

    // Phase
    assert_eq!(X(0).phase(), QuarterPhase::PlusOne);
    assert_eq!((-X(0)).phase(), QuarterPhase::MinusOne);

    // Qubit positions
    assert_eq!(a.x_positions(), vec![0]);  // X on qubit 0
    assert_eq!(a.z_positions(), vec![1]);  // Z on qubit 1
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_4() {
    use pecos_core::PauliString;
    let p: PauliString = "XZI".parse().unwrap();    // X(0) & Z(1)
    let q: PauliString = "+XZZXI".parse().unwrap(); // with explicit phase
    let r: PauliString = "-iYX".parse().unwrap();   // -i * Y(0) * X(1)
}


// Hadamard on qubit 0: X -> Z, Z -> X

#[test]
fn test_user_guide_quantum_operator_algebra_rust_5() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::clifford_rep::CliffordRep;
    let h = CliffordRep::h(0);
    assert_eq!(*h.x_image(0), Z(0));  // H X H^dag = Z
    assert_eq!(*h.z_image(0), X(0));  // H Z H^dag = X

    // Composition
    let hh = h.compose(&h);  // H^2 = I (up to phase)

    // Transform a Pauli string through a Clifford
    let stabilizer = Zs([0, 1]);
    let transformed = h.apply(&stabilizer);
    // H on qubit 0 turns Z(0)Z(1) into X(0)Z(1)
}


// Named gates

#[test]
fn test_user_guide_quantum_operator_algebra_rust_6() {
    use pecos_core::unitary_rep::*;
    use pecos_core::Angle64;
    let circuit = T(1) * CX(0, 1) * H(0);  // apply H, then CX, then T

    // Check Clifford-ness
    assert!(!circuit.is_clifford());    // T is not Clifford
    assert!((CX(0, 1) * H(0)).is_clifford());

    // Tensor product
    let parallel = H(0) & H(1);  // H on both qubits simultaneously

    // Adjoint
    let inv = circuit.dg();  // T^dag * CX^dag * H^dag

    // Rotation gates
    let rz = RZ(Angle64::HALF_TURN / 4, 0);  // Rz(pi/4) on qubit 0

    // Multi-qubit gate constructors
    let cx_pair = CXs([(0, 1), (2, 3)]);  // CX on two pairs
    let h_all = Hs([0, 1, 2]);            // H on three qubits
}


// Measurement and preparation

#[test]
fn test_user_guide_quantum_operator_algebra_rust_7() {
    use pecos_core::op::*;
    let mz = MZ(0);           // Z-basis measurement on qubit 0
    let mx = MX(1);           // X-basis measurement on qubit 1
    let pz = PZ(0);           // Prepare |0> on qubit 0

    // Noise channels
    let depol = Depolarizing(0.01, 0);            // 1% depolarizing on qubit 0
    let deph = Dephasing(0.02, 1);                // 2% dephasing on qubit 1
    let amp_damp = AmplitudeDamping(0.05, 0);     // T1 decay
    let phase_damp = PhaseDamping(0.03, 0);       // T2 dephasing
    let erasure = Erasure(0.01, 0);               // Erasure channel
    let reset = Reset(0);                         // Reset to |0>
    let leak = Leakage(0.001, 0);                 // Leakage to non-computational state

    // Custom Pauli channel
    let pauli_ch = PauliChannel(0.01, 0.01, 0.01, 0);  // px, py, pz
}


// Pauli & Pauli stays Pauli

#[test]
fn test_user_guide_quantum_operator_algebra_rust_8() {
    use pecos_core::op::*;
    let p = X(0) & Y(3);
    assert!(p.is_pauli());

    // Pauli & Clifford promotes to Clifford
    let c = X(0) & H(3);
    assert!(c.is_clifford());

    // Adding a non-Clifford promotes to Unitary
    let u = X(0) & H(3) & T(5);
    assert!(u.is_unitary());

    // Adding a measurement promotes to Channel
    let ch = H(0) & MZ(1);
    assert!(ch.is_channel());
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_9() {
    use pecos_core::op::*;
    let p = X(0) & Z(1);
    let ps = p.as_pauli().unwrap();  // borrow the inner PauliString

    let c = H(0) & X(1);
    let cr = c.as_clifford().unwrap();  // borrow the inner CliffordRep

    // Consuming extraction with promotion
    let u = (X(0) & H(1)).into_unitary().unwrap();  // promotes Clifford to UnitaryRep

    // Every Op can become a Channel
    let ch = (H(0) & T(1)).into_channel();  // always succeeds
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_10() {
    use pecos_core::op::*;
    let circuit = T(1) * CX(0, 1) * H(0);
    let inverse = circuit.dg();  // works for Pauli, Clifford, Unitary

    // Channels are not invertible -- dg() panics, use try_dg()
    let m = MZ(0);
    assert!(m.try_dg().is_none());
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_11() {
    use pecos_core::op::*;
    let circuit = CX(0, 3) & H(5);
    assert_eq!(circuit.num_qubits(), 6);     // spans qubits 0..5
    assert_eq!(circuit.qubits(), vec![0, 1, 2, 3, 4, 5]);  // full range
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_12() {
    use pecos_core::pauli::constructors::*;
    use pecos_quantum::PauliSequence;
    let seq = PauliSequence::new(vec![
        Zs([0, 1]),
        Zs([1, 2]),
        Zs([0, 2]),  // linearly dependent on the first two
    ]);

    // GF(2) rank: number of linearly independent Paulis
    assert_eq!(seq.rank(), 2);

    // Membership in GF(2) span (ignoring phase)
    assert!(seq.contains(&Zs([0, 2])));   // Z(0)Z(2) = product of first two
    assert!(!seq.contains(&X(0)));         // X not in Z-span

    // Commutativity check
    assert!(seq.is_abelian());  // all Z-type, so commute

    // Row reduction to independent generators
    let reduced = seq.row_reduce();
    assert_eq!(reduced.len(), 2);
}



#[test]
fn test_user_guide_quantum_operator_algebra_rust_13() {
    use pecos_core::pauli::constructors::*;
    use pecos_quantum::PauliSet;
    let mut set = PauliSet::new();
    set.insert(X(0));
    set.insert(Z(1));
    set.insert(X(0));  // duplicate, ignored

    assert_eq!(set.len(), 2);
    assert!(set.contains(&X(0)));

    // Set operations
    let other = PauliSet::from_iter(vec![X(0), Y(2)]);
    let union = set.union(&other);
    assert_eq!(union.len(), 3);  // X(0), Z(1), Y(2)
}


// Generators with imaginary phase

#[test]
fn test_user_guide_quantum_operator_algebra_rust_14() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::pauli::algebra::i;
    use pecos_quantum::PauliGroup;
    let group = PauliGroup::new(vec![
        i * X(0) & Y(1),   // phase +i, order 4
        Z(2),               // phase +1, order 2
    ]).unwrap();

    assert_eq!(group.rank(), 2);
    assert!(group.contains_minus_identity());  // (iXY)^2 = -I

    // Validation: anticommuting generators are rejected
    let err = PauliGroup::new(vec![X(0), Z(0)]);
    assert!(err.is_err());
}


// Repetition code stabilizers

#[test]
fn test_user_guide_quantum_operator_algebra_rust_15() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_core::pauli::constructors::*;
    use pecos_core::clifford_rep::CliffordRep;
    use pecos_quantum::PauliStabilizerGroup;
    let stab = PauliStabilizerGroup::new(vec![
        Zs([0, 1]),
        Zs([1, 2]),
    ]).unwrap();

    assert_eq!(stab.rank(), 2);

    // GF(2) membership (is ZIZ in the stabilizer group?)
    assert!(stab.contains(&Zs([0, 2])));

    // Phase-aware membership
    assert!(stab.contains_with_phase(&Zs([0, 2])));   // +ZIZ is in the group
    assert!(!stab.contains_with_phase(&(-Zs([0, 2])))); // -ZIZ is not

    // Clifford transformation: conjugate all generators
    let h = CliffordRep::h(0);
    let transformed = stab.apply_clifford(&h);
    // Z(0)Z(1) becomes X(0)Z(1) under H on qubit 0
    Ok(())
}


// Upward (widening) -- always succeeds

#[test]
fn test_user_guide_quantum_operator_algebra_rust_16() {
    use pecos_core::pauli::constructors::*;
    use pecos_quantum::{PauliGroup, PauliSequence, PauliSet, PauliStabilizerGroup};
    let stab = PauliStabilizerGroup::new(vec![Zs([0, 1])]).unwrap();
    let group: PauliGroup = stab.clone().into();        // drop phase constraint
    let seq: PauliSequence = group.into();               // drop commutativity constraint
    let set: PauliSet = PauliSet::from_iter(vec![Zs([0, 1])]);

    // Downward (narrowing) -- validates constraints
    let seq = PauliSequence::new(vec![Zs([0, 1]), Zs([1, 2])]);
    let group: PauliGroup = seq.try_into().unwrap();     // checks commutativity
    let stab: PauliStabilizerGroup = group.try_into().unwrap(); // checks real phases

    // From strings
    let stab = PauliStabilizerGroup::from_strs(&["ZZI", "IZZ"]).unwrap();
    let group = PauliGroup::from_strs(&["ZZI", "IZZ"]).unwrap();
    let seq = PauliSequence::from_strs(&["XZ", "ZX"]).unwrap();  // can anticommute
}


// Build a stabilizer group

#[test]
fn test_user_guide_quantum_operator_algebra_rust_17() {
    use pecos_core::pauli::constructors::*;
    use pecos_qec::StabilizerCode;
    use pecos_quantum::PauliStabilizerGroup;
    let group = PauliStabilizerGroup::new(vec![
        Zs([0, 1]),
        Zs([1, 2]),
    ]).unwrap();

    // Wrap in a StabilizerCode for QEC analysis
    let code = StabilizerCode::from_group(group);
    assert_eq!(code.num_logical_qubits(), 1);
    assert_eq!(code.distance(), Some(1));

    // Or use standard constructors directly
    let steane = StabilizerCode::steane();
    assert_eq!(steane.distance(), Some(3));
}
