//! Auto-generated Rust tests from user-guide/fault-tolerance.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


// Define a 3-qubit bit-flip code

#[test]
fn test_user_guide_fault_tolerance_rust_1() {
    use pecos_core::{PauliString, QuarterPhase};
    use pecos_core::pauli::{Xs, Zs};
    use pecos_qec::{ErrorClass, StabilizerCodeSpec, StabilizerFlipChecker};
    let code = StabilizerCodeSpec::builder(3)
        .check(Zs([0, 1]))
        .check(Zs([1, 2]))
        .logical_z(Zs([0, 1, 2]))
        .logical_x(Xs([0]))
        .build()
        .unwrap();

    let checker = StabilizerFlipChecker::new(&code);
}



#[test]
fn test_user_guide_fault_tolerance_rust_2() {
    use pecos_core::pauli::*;
    use pecos_qec::{ErrorClass, StabilizerCodeSpec, StabilizerFlipChecker};
    let code = StabilizerCodeSpec::builder(3)
        .check(Zs([0, 1]))
        .check(Zs([1, 2]))
        .logical_z(Zs([0, 1, 2]))
        .logical_x(Xs([0]))
        .build()
        .unwrap();
    let checker = StabilizerFlipChecker::new(&code);

    // X error on qubit 0 -- detectable (flips first stabilizer, also hits logical X)
    let result = checker.classify_error(&X(0));
    assert!(result.is_detectable());
    assert!(result.causes_logical_error());

    // Z error on qubit 0 -- undetectable (commutes with all Z-stabilizers)
    // but causes logical error (anticommutes with logical X)
    let result = checker.classify_error(&Z(0));
    assert!(matches!(result, ErrorClass::UndetectableLogical { .. }));
}



#[test]
fn test_user_guide_fault_tolerance_rust_3() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_core::pauli::*;
    use pecos_qec::{StabilizerCodeSpec, StabilizerFlipChecker};
    let code = StabilizerCodeSpec::builder(3)
        .check(Zs([0, 1])).check(Zs([1, 2]))
        .logical_z(Zs([0, 1, 2])).logical_x(Xs([0]))
        .build().unwrap();
    let checker = StabilizerFlipChecker::new(&code);

    let flips = checker.compute_flips(&X(1));
    println!("Flipped stabilizers: {:?}", flips.stabilizers);  // {0, 1}
    println!("Flipped logical Zs: {:?}", flips.logical_zs);
    println!("Flipped logical Xs: {:?}", flips.logical_xs);
    println!("Syndrome: {:?}", flips.syndrome(2));  // [true, true]
    Ok(())
}



#[test]
fn test_user_guide_fault_tolerance_rust_4() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_core::pauli::{Xs, Zs};
    use pecos_qec::{StabilizerCodeSpec, StabilizerFlipChecker};
    let code = StabilizerCodeSpec::builder(3)
        .check(Zs([0, 1])).check(Zs([1, 2]))
        .logical_z(Zs([0, 1, 2])).logical_x(Xs([0]))
        .build().unwrap();
    let checker = StabilizerFlipChecker::new(&code);

    // Analyze all weight-1 errors
    let analysis = checker.analyze_weight(1);

    println!("Total errors: {}", analysis.total_errors);
    println!("Stabilizer (harmless): {}", analysis.stabilizer_errors);
    println!("Detectable: {}", analysis.detectable_no_logical);
    println!("Undetectable logical: {}", analysis.undetectable_logical);
    println!("Detectable with logical: {}", analysis.detectable_with_logical);

    // Is the code fault-tolerant at weight 1?
    println!("Fault-tolerant: {}", analysis.is_fault_tolerant());
    Ok(())
}



#[test]
fn test_user_guide_fault_tolerance_rust_5() {
    use pecos_core::pauli::{Xs, Zs};
    use pecos_qec::{StabilizerCodeSpec, StabilizerFlipChecker};
    let code = StabilizerCodeSpec::builder(3)
        .check(Zs([0, 1])).check(Zs([1, 2]))
        .logical_z(Zs([0, 1, 2])).logical_x(Xs([0]))
        .build().unwrap();
    let checker = StabilizerFlipChecker::new(&code);

    // Only X errors (bit-flip)
    let x_analysis = checker.analyze_weight_with_types(1, true, false, false);

    // Only Z errors (phase-flip)
    let z_analysis = checker.analyze_weight_with_types(1, false, false, true);

    // X and Z but not Y
    let xz_analysis = checker.analyze_weight_with_types(1, true, false, true);
}


// Build a syndrome extraction circuit for the 3-qubit bit-flip code

#[test]
fn test_user_guide_fault_tolerance_rust_6() {
    use pecos_qec::PauliPropChecker;
    use pecos_quantum::TickCircuit;
    let mut circuit = TickCircuit::new();
    circuit.tick().pz(&[0, 1, 2, 3, 4]);    // Initialize all qubits
    circuit.tick().cx(&[(0, 3), (1, 4)]);    // CNOT: data -> ancilla
    circuit.tick().cx(&[(1, 3), (2, 4)]);    // Second round of CNOTs
    circuit.tick().mz(&[3, 4]);              // Measure ancillas

    let checker = PauliPropChecker::new(&circuit);

    // Define syndrome ancillas and logical operators
    let z_ancillas = &[3, 4];
    let x_ancillas: &[usize] = &[];
    let logicals: &[(&[usize], &[usize])] = &[(&[], &[0, 1, 2])]; // Z logical

    // Analyze all single-fault locations
    let results = checker.analyze_all_faults(z_ancillas, x_ancillas, logicals);
    println!("Total fault locations analyzed: {}", results.len());
}


// Build a syndrome extraction gadget

#[test]
fn test_user_guide_fault_tolerance_rust_7() {
    use pecos_qec::fault_tolerance::{GadgetChecker, GadgetConfig};
    use pecos_quantum::TickCircuit;
    let mut circuit = TickCircuit::new();
    // Data qubits 0,1,2 are INPUT (not initialized here)
    circuit.tick().pz(&[3, 4]);           // Initialize ancillas only
    circuit.tick().cx(&[(0, 3), (1, 4)]); // CNOTs from data to ancilla
    circuit.tick().cx(&[(1, 3), (2, 4)]);
    circuit.tick().mz(&[3, 4]);           // Measure ancillas
    // Data qubits 0,1,2 are OUTPUT (not measured here)

    let config = GadgetConfig::syndrome_extraction()
        .with_input_qubits(&[0, 1, 2])   // Data qubits enter with potential errors
        .with_output_qubits(&[0, 1, 2])  // Data qubits leave (may have errors)
        .with_ancilla_qubits(&[3, 4])    // Initialized and measured within gadget
        .with_z_ancillas(&[3, 4])        // For syndrome extraction
        .with_logical_z(&[], &[0, 1, 2]); // Z logical operator

    let checker = GadgetChecker::new(&circuit, config);
    let analysis = checker.analyze(1); // Check 1-fault tolerance

    println!("Is 1-FT: {}", analysis.is_fault_tolerant());
    println!("Total tested: {}", analysis.total_tested);
    println!("Undetected logical: {}", analysis.undetected_logical);
    println!("Excessive output: {}", analysis.excessive_output);
}


#[test]
fn test_user_guide_fault_tolerance_rust_8() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_qec::DemBuilder;
    use pecos_qec::fault_tolerance::propagator::DagFaultAnalyzer;
    use pecos_quantum::DagCircuit;
    // Build a simple parity check circuit
    let mut dag = DagCircuit::new();
    dag.pz(&[2]);       // prepare ancilla
    dag.cx(&[(0, 2)]);  // parity check
    dag.cx(&[(1, 2)]);
    dag.mz(&[2]);       // measure syndrome

    // Analyze faults to build influence map
    let analyzer = DagFaultAnalyzer::new(&dag);
    let influence_map = analyzer.build_influence_map();

    // Define detectors and observables
    let detectors_json = r#"[{"id": 0, "records": [-1]}]"#;
    let observables_json = r"[]";


// Build DEM from a fault influence map
let dem = DemBuilder::new(&influence_map)
    .with_noise(0.01, 0.01, 0.01, 0.01)  // p1, p2, p_meas, p_prep
    .with_detectors_json(detectors_json)?
    .with_observables_json(observables_json)?
    .build();

println!("DEM has {} detectors, {} contributions",
    dem.num_detectors(), dem.num_contributions());
    Ok(())
}


#[test]
fn test_user_guide_fault_tolerance_rust_9() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_core::pauli::{Xs, Zs};
    use pecos_qec::{DemBuilder, DistanceSearchConfig, StabilizerCodeSpec, calculate_distance};
    use pecos_qec::fault_tolerance::propagator::DagFaultAnalyzer;
    use pecos_quantum::DagCircuit;
    // Build a simple parity check circuit
    let mut dag = DagCircuit::new();
    dag.pz(&[2]);       // prepare ancilla
    dag.cx(&[(0, 2)]);  // parity check
    dag.cx(&[(1, 2)]);
    dag.mz(&[2]);       // measure syndrome

    // Analyze faults to build influence map
    let analyzer = DagFaultAnalyzer::new(&dag);
    let influence_map = analyzer.build_influence_map();

    // Define detectors and observables
    let detectors_json = r#"[{"id": 0, "records": [-1]}]"#;
    let observables_json = r"[]";


let code = StabilizerCodeSpec::builder(7)
    .check(Xs([0, 2, 4, 6]))
    .check(Xs([1, 2, 5, 6]))
    .check(Xs([3, 4, 5, 6]))
    .check(Zs([0, 2, 4, 6]))
    .check(Zs([1, 2, 5, 6]))
    .check(Zs([3, 4, 5, 6]))
    .logical_z(Zs([0, 2, 4, 6]))
    .logical_x(Xs([0, 2, 4, 6]))
    .build()
    .unwrap();

// Basic distance calculation
let result = calculate_distance(&code, &DistanceSearchConfig::default());
if let Some(r) = result {
    println!("Distance: {}", r.distance);
    println!("Min-weight operator: {}", r.min_weight_operator);
}

// CSS-only search (faster for CSS codes)
let result = calculate_distance(&code, &DistanceSearchConfig::css());

// Bounded search (stop at weight 5)
let result = calculate_distance(&code, &DistanceSearchConfig::with_max_weight(5));
    Ok(())
}


#[test]
fn test_user_guide_fault_tolerance_rust_10() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_core::pauli::{Xs, Zs};
    use pecos_qec::{DemBuilder, DistanceSearchConfig, StabilizerCodeSpec, find_min_weight_logicals_with_info};
    use pecos_qec::fault_tolerance::propagator::DagFaultAnalyzer;
    use pecos_quantum::DagCircuit;
    // Build a simple parity check circuit
    let mut dag = DagCircuit::new();
    dag.pz(&[2]);       // prepare ancilla
    dag.cx(&[(0, 2)]);  // parity check
    dag.cx(&[(1, 2)]);
    dag.mz(&[2]);       // measure syndrome

    // Analyze faults to build influence map
    let analyzer = DagFaultAnalyzer::new(&dag);
    let influence_map = analyzer.build_influence_map();

    // Define detectors and observables
    let detectors_json = r#"[{"id": 0, "records": [-1]}]"#;
    let observables_json = r"[]";


let code = StabilizerCodeSpec::builder(7)
    .check(Xs([0, 2, 4, 6]))
    .check(Xs([1, 2, 5, 6]))
    .check(Xs([3, 4, 5, 6]))
    .check(Zs([0, 2, 4, 6]))
    .check(Zs([1, 2, 5, 6]))
    .check(Zs([3, 4, 5, 6]))
    .logical_z(Zs([0, 2, 4, 6]))
    .logical_x(Xs([0, 2, 4, 6]))
    .build()
    .unwrap();

let logicals = find_min_weight_logicals_with_info(&code, &DistanceSearchConfig::default());
for op in &logicals {
    println!("Weight {}: {} (equivalent to {})",
        op.weight, op.operator, op.equivalence_string());
}
    Ok(())
}


#[test]
fn test_user_guide_fault_tolerance_rust_11() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_core::pauli::Zs;
    use pecos_qec::{DemBuilder, discover_logical_operators};
    use pecos_qec::fault_tolerance::propagator::DagFaultAnalyzer;
    use pecos_quantum::DagCircuit;
    // Build a simple parity check circuit
    let mut dag = DagCircuit::new();
    dag.pz(&[2]);       // prepare ancilla
    dag.cx(&[(0, 2)]);  // parity check
    dag.cx(&[(1, 2)]);
    dag.mz(&[2]);       // measure syndrome

    // Analyze faults to build influence map
    let analyzer = DagFaultAnalyzer::new(&dag);
    let influence_map = analyzer.build_influence_map();

    // Define detectors and observables
    let detectors_json = r#"[{"id": 0, "records": [-1]}]"#;
    let observables_json = r"[]";


// Define stabilizers for the 3-qubit bit-flip code
let stabilizers = vec![Zs([0, 1]), Zs([1, 2])];

// Discover logical operators
let result = discover_logical_operators(3, &stabilizers).unwrap();

println!("Logical qubits: {}", result.num_logical_qubits);  // 1
println!("Logical Xs: {:?}", result.logical_xs);
println!("Logical Zs: {:?}", result.logical_zs);
println!("Destabilizers: {:?}", result.destabilizers);
    Ok(())
}


#[test]
fn test_user_guide_fault_tolerance_rust_12() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_qec::DemBuilder;
    use pecos_qec::fault_tolerance::propagator::DagFaultAnalyzer;
    use pecos_quantum::DagCircuit;
    use pecos_qec::{
StabilizerCode, StabilizerCodeSpec, StabilizerFlipChecker,
calculate_distance, DistanceSearchConfig,
};
    // Build a simple parity check circuit
    let mut dag = DagCircuit::new();
    dag.pz(&[2]);       // prepare ancilla
    dag.cx(&[(0, 2)]);  // parity check
    dag.cx(&[(1, 2)]);
    dag.mz(&[2]);       // measure syndrome

    // Analyze faults to build influence map
    let analyzer = DagFaultAnalyzer::new(&dag);
    let influence_map = analyzer.build_influence_map();

    // Define detectors and observables
    let detectors_json = r#"[{"id": 0, "records": [-1]}]"#;
    let observables_json = r"[]";


// 1. Start from a code definition
let code = StabilizerCode::steane();

// 2. Convert to StabilizerCodeSpec (discovers logicals)
let spec = StabilizerCodeSpec::from_stabilizer_code(&code).unwrap();

// 3. Verify algebraic correctness
spec.verify().unwrap();

// 4. Compute distance
let dist = calculate_distance(&spec, &DistanceSearchConfig::default());
println!("Distance: {:?}", dist.as_ref().map(|r| r.distance));

// 5. Check fault tolerance at weight 1
let checker = StabilizerFlipChecker::new(&spec);
let analysis = checker.analyze_weight(1);
println!("Fault-tolerant at weight 1: {}", analysis.is_fault_tolerant());

// 6. For a distance-3 code, also check weight 2
if dist.as_ref().is_some_and(|r| r.distance >= 3) {
    let analysis_2 = checker.analyze_weight(2);
    println!("Fault-tolerant at weight 2: {}", analysis_2.is_fault_tolerant());
}
    Ok(())
}
