//! Auto-generated Rust tests from user-guide/circuit-representation.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_circuit_representation_rust_1() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit, TickGateError};

// Fluent builder API
let mut circuit = DagCircuit::new();
circuit.h(&[0]).cx(&[(0, 1)]).rz(0.5, &[0]).mz(&[0]);

// Query properties
println!("Gates: {}", circuit.gate_count());
println!("Depth: {}", circuit.depth());
println!("Width: {}", circuit.width());

}


#[test]
fn test_user_guide_circuit_representation_rust_2() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

let mut circuit = DagCircuit::new();

// Single-qubit gates
circuit.h(&[0]);       // Hadamard
circuit.x(&[1]);       // Pauli X
circuit.y(&[2]);       // Pauli Y
circuit.z(&[3]);       // Pauli Z
circuit.sz(&[0]);      // S gate
circuit.szdg(&[0]);    // S-dagger
circuit.t(&[0]);       // T gate
circuit.tdg(&[0]);     // T-dagger

// Rotation gates (angle in radians)
circuit.rx(3.14159, &[0]);
circuit.ry(1.5708, &[1]);
circuit.rz(0.7854, &[2]);

// Two-qubit gates
circuit.cx(&[(0, 1)]);
circuit.szz(&[(0, 1)]);
circuit.rzz(0.5, &[(0, 1)]);

// Measurement and preparation
circuit.mz(&[0]);
circuit.pz(&[1]);

// Chaining
circuit.h(&[0]).cx(&[(0, 1)]).h(&[0]).mz(&[0]);

}


#[test]
fn test_user_guide_circuit_representation_rust_3() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

let mut circuit = DagCircuit::new();

// Attach metadata to the last gate
circuit.h(&[0]).meta("error_rate", Attribute::Float(0.001));

// Multiple metadata entries
circuit.cx(&[(0, 1)]).meta("duration_ns", Attribute::Int(50));

// Measurements return refs (not &mut Self), so chain separately
circuit.mz(&[0]);
circuit.meta("basis", Attribute::String("Z".into()));

}


#[test]
fn test_user_guide_circuit_representation_rust_4() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};
    let mut circuit = DagCircuit::new();
circuit.h(&[0]).cx(&[(0, 1)]).h(&[1]).cx(&[(1, 2)]);
circuit.mz(&[0]);
circuit.mz(&[1]);
circuit.mz(&[2]);

// Basic metrics
println!("Total gates: {}", circuit.gate_count());
println!("Circuit depth: {}", circuit.depth());
println!("Circuit width: {}", circuit.width());
println!("Qubits used: {:?}", circuit.qubits());

// Gate counts
println!("Single-qubit gates: {}", circuit.single_qubit_gate_count());
println!("Two-qubit gates: {}", circuit.two_qubit_gate_count());

// Topological iteration
for node_id in circuit.topological_order() {
    if let Some(gate) = circuit.gate(node_id) {
        println!("Node {}: {:?}", node_id, gate);
    }
}

// Layer iteration
for (i, layer) in circuit.layers().enumerate() {
    println!("Layer {}: {:?}", i, layer);
}

}


#[test]
fn test_user_guide_circuit_representation_rust_5() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

let mut circuit = DagCircuit::new();

// Add gates manually
let h_node = circuit.add_gate(Gate::h(&[0]));
let cx_node = circuit.add_gate(Gate::cx(&[(0, 1)]));

// Connect gates on qubit 0
circuit.connect(h_node, cx_node, QubitId::from(0)).unwrap();

// Query connections
println!("Predecessors of CX: {:?}", circuit.predecessors(cx_node));
println!("Successors of H: {:?}", circuit.successors(h_node));

}


#[test]
fn test_user_guide_circuit_representation_rust_6() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

let mut circuit = TickCircuit::new();

// First tick: parallel gates
circuit.tick().h(&[0, 1, 2]);

// Second tick: entangling layer
circuit.tick().cx(&[(0, 1), (2, 3)]);

// Third tick: measurements
circuit.tick().mz(&[0, 1]);

println!("Number of ticks: {}", circuit.num_ticks());
println!("Total gates: {}", circuit.gate_count());
println!("Gate batches: {}", circuit.gate_batch_count());

}


#[test]
fn test_user_guide_circuit_representation_rust_7() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

let mut circuit = TickCircuit::new();
let mut tick = circuit.tick();

tick.h(&[0]);
// This would error: qubit 0 already used
// tick.cx(&[(0, 1)]);

// Use try_add_gate for fallible operations
if let Err(pecos::quantum::TickGateError::QubitConflict(e)) =
    tick.try_add_gate(Gate::cx(&[(0, 1)]))
{
    println!("Conflict on qubits: {:?}", e.conflicting_qubits);
}

}


#[test]
fn test_user_guide_circuit_representation_rust_8() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};
    let mut circuit = TickCircuit::new();

// Add metadata to a tick
let mut tick = circuit.tick();
tick.meta("round", Attribute::Int(1));
tick.h(&[0]).meta("error_rate", Attribute::Float(0.001));

// Circuit-level metadata
circuit.set_meta("name", Attribute::String("Bell state".into()));

}


#[test]
fn test_user_guide_circuit_representation_rust_9() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

// TickCircuit -> DagCircuit
let mut tick_circuit = TickCircuit::new();
tick_circuit.tick().h(&[0, 1]);
tick_circuit.tick().cx(&[(0, 1)]);

let dag_circuit = DagCircuit::from(tick_circuit);

// DagCircuit -> TickCircuit
let tick_circuit2 = TickCircuit::from(dag_circuit);

}


#[test]
fn test_user_guide_circuit_representation_rust_10() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

let mut graph = DiGraph::new();

// Add nodes
let n0 = graph.add_node();
let n1 = graph.add_node();
let n2 = graph.add_node();

// Add edges with weights
graph.add_edge(n0, n1).weight(1.0);
graph.add_edge(n1, n2).weight(2.0);
graph.add_edge(n0, n2).weight(5.0);

// Query structure
println!("Predecessors of n2: {:?}", graph.predecessors(n2));
println!("Successors of n0: {:?}", graph.successors(n0));
println!("In-degree of n2: {}", graph.in_degree(n2));
println!("Out-degree of n0: {}", graph.out_degree(n0));

}


#[test]
fn test_user_guide_circuit_representation_rust_11() {
    use pecos::core::{Gate, QubitId};
    use pecos::dag::DAG;
    use pecos::digraph::DiGraph;
    use pecos::quantum::{Attribute, DagCircuit, TickCircuit};

let mut dag = DAG::new();

// Add nodes
let n0 = dag.add_node();
let n1 = dag.add_node();
let n2 = dag.add_node();

// Add edges (cycle detection)
dag.add_edge(n0, n1).unwrap();
dag.add_edge(n1, n2).unwrap();
// dag.add_edge(n2, n0)  // Would return Err: creates cycle!

// Topological operations
println!("Topological order: {:?}", dag.topological_sort());
println!("Roots: {:?}", dag.roots());
println!("Leaves: {:?}", dag.leaves());
println!("Depth: {}", dag.depth());

// Ancestry queries
println!("Ancestors of n2: {:?}", dag.ancestors(n2));
println!("Descendants of n0: {:?}", dag.descendants(n0));

// Layer iteration
for layer in dag.layers(dag.roots()) {
    println!("Layer: {:?}", layer);
}

}
