//! Auto-generated Rust tests from user-guide/wasm-foreign-objects.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_wasm_foreign_objects_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::wasm::WasmForeignObject;
    use std::fs;
    let tmpdir = tempfile::tempdir()?;
    let wasm_path = tmpdir.path().join("math_functions.wasm");
    let wat = r#"(module
      (global $accumulator (mut i32) (i32.const 0))
      (func $init)
      (func $shot_reinit (i32.const 0) (global.set $accumulator))
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (func $mul (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.mul))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "shot_reinit" (func $shot_reinit))
      (export "add" (func $add))
      (export "mul" (func $mul))
      (export "memory" (memory 0))
    )"#;
    fs::write(&wasm_path, wat)?;


// From a file path with default timeout (1 second)
let wasm = WasmForeignObject::new(&wasm_path)?;

// With custom timeout
let wasm = WasmForeignObject::with_timeout(&wasm_path, 5.0)?;

// With custom timeout and memory limit
let wasm = WasmForeignObject::with_limits(
    wasm_path.to_str().unwrap(),
    5.0,                      // timeout in seconds
    Some(10 * 1024 * 1024),   // memory limit in bytes
)?;

    Ok(())
}



#[test]
fn test_user_guide_wasm_foreign_objects_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::wasm::WasmForeignObject;
    let wasm_bytes: Vec<u8> = br#"(module
      (func $init)
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "add" (func $add))
      (export "memory" (memory 0))
    )"#.to_vec();


// From bytes with default timeout
let wasm = WasmForeignObject::from_bytes(&wasm_bytes)?;

// With custom timeout
let wasm = WasmForeignObject::from_bytes_with_timeout(&wasm_bytes, 5.0)?;

// With custom timeout and memory limit
let wasm = WasmForeignObject::from_bytes_with_limits(
    &wasm_bytes,
    5.0,
    Some(10 * 1024 * 1024),
)?;

    Ok(())
}



#[test]
fn test_user_guide_wasm_foreign_objects_rust_3() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::wasm::{ForeignObject, WasmForeignObject};
    use std::fs;
    let tmpdir = tempfile::tempdir()?;
    let wat_path = tmpdir.path().join("math.wat");
    let wat = r#"(module
      (func $init)
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (func $mul (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.mul))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "add" (func $add))
      (export "mul" (func $mul))
      (export "memory" (memory 0))
    )"#;
    fs::write(&wat_path, wat)?;


let mut wasm = WasmForeignObject::new(&wat_path)?;
wasm.init()?;

// Execute functions
let result = wasm.exec("add", &[5, 3])?;
println!("5 + 3 = {:?}", result);  // Output: 5 + 3 = [8]

// List available functions
println!("{:?}", wasm.get_funcs());

    Ok(())
}



#[test]
fn test_user_guide_wasm_foreign_objects_rust_4() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;
    use std::fs;
    let tmpdir = tempfile::tempdir()?;
    let wat_path = tmpdir.path().join("math_add.wat");
    let wat = r#"(module
      (func $init)
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "add" (func $add))
      (export "memory" (memory 0))
    )"#;
    fs::write(&wat_path, wat)?;


let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";

    qreg q[2];
    creg c[2];
    creg result[8];

    result = add(3, 5);

    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

// Build engine with WASM foreign functions
let results = qasm_engine()
    .qasm(qasm_code)
    .wasm(wat_path.to_str().unwrap())  // Load WASM module for foreign functions
    .to_sim()
    .run(100)?;

    Ok(())
}



#[test]
fn test_user_guide_wasm_foreign_objects_rust_5() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::wasm::WasmForeignObject;
    use std::fs;
    let tmpdir = tempfile::tempdir()?;
    let wat_path = tmpdir.path().join("compute.wat");
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write(&wat_path, wat)?;

    // 5 second timeout
let wasm = WasmForeignObject::with_timeout(&wat_path, 5.0)?;

    Ok(())
}



#[test]
fn test_user_guide_wasm_foreign_objects_rust_6() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::wasm::WasmForeignObject;
    use std::fs;
    let tmpdir = tempfile::tempdir()?;
    let wat_path = tmpdir.path().join("compute.wat");
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write(&wat_path, wat)?;

    // Limit to 10 MB
let wasm = WasmForeignObject::with_limits(
    wat_path.to_str().unwrap(),
    1.0,                      // timeout
    Some(10 * 1024 * 1024),   // memory limit
)?;

// No limit
let wasm = WasmForeignObject::with_limits(wat_path.to_str().unwrap(), 1.0, None)?;

    Ok(())
}



#[test]
fn test_user_guide_wasm_foreign_objects_rust_7() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::wasm::WasmForeignObject;
    use std::fs;
    let tmpdir = tempfile::tempdir()?;
    let wat_path = tmpdir.path().join("clone_test.wat");
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write(&wat_path, wat)?;

    let wasm = WasmForeignObject::new(&wat_path)?;

// Get the WASM bytes
let bytes = wasm.wasm_bytes();

// Create a new instance from bytes
let wasm2 = WasmForeignObject::from_bytes(bytes)?;

    Ok(())
}



#[test]
fn test_user_guide_wasm_foreign_objects_rust_8() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::wasm::WasmForeignObject;
    use std::fs;
    let tmpdir = tempfile::tempdir()?;
    let wat_path = tmpdir.path().join("clone_test.wat");
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write(&wat_path, wat)?;


// File not found error - this intentionally fails
match WasmForeignObject::new("nonexistent.wasm") {
    Err(e) => println!("Expected error: {}", e),
    Ok(_) => println!("Unexpected success"),
}

    Ok(())
}

