//! Auto-generated Rust tests from user-guide/stabilizer-tensor-networks.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_stabilizer_tensor_networks_rust_1() {
    use pecos_core::{Angle64, QubitId};
    use pecos_simulators::{ArbitraryRotationGateable, CliffordGateable};
    use pecos_stab_tn::stab_mps::StabMps;
    let mut sim = StabMps::builder(2).seed(7).build();
    sim.h(&[QubitId(0)]);
    sim.cx(&[(QubitId(0), QubitId(1))]);
    sim.rz(Angle64::QUARTER_TURN / 2_u64, &[QubitId(1)]);

    let outcome = sim.mz(&[QubitId(0)])[0].outcome;
    sim.flush();
    let bits = [outcome, outcome];
    assert!((sim.prob_bitstring(&bits) - 1.0).abs() < 1e-12);
}
