//! Auto-generated Rust tests from user-guide/stabilizer-codes.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_stabilizer_codes_rust_1() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;

// Single-qubit Paulis
let x0 = X(0);       // X on qubit 0
let z3 = Z(3);       // Z on qubit 3
let y1 = Y(1);       // Y on qubit 1

// Multi-qubit (same type) via array constructors
let zz = Zs([0, 1]);         // ZZ on qubits 0,1
let xxxx = Xs([0, 1, 2, 3]); // XXXX on qubits 0-3

// Mixed Paulis via the & operator
let xzzx = X(0) & Z(1) & Z(2) & X(3);  // XZZXI...

// Commutation checks
// X and Z on different qubits commute:
assert!(x0.commutes_with(&z3));
// X and Z on the SAME qubit anticommute:
assert!(!X(0).commutes_with(&Z(0)));

}


#[test]
fn test_user_guide_stabilizer_codes_rust_2() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::StabilizerCode;

// 3-qubit bit-flip repetition code: generators ZZI, IZZ
let group = pecos_quantum::PauliStabilizerGroup::new(vec![
    Zs([0, 1]),
    Zs([1, 2]),
]).unwrap();

let code = StabilizerCode::from_group(group);

// Or use the built-in constructor:
let code = StabilizerCode::repetition(3);

}


#[test]
fn test_user_guide_stabilizer_codes_rust_3() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::StabilizerCode;

let code = StabilizerCode::steane();

println!("n = {}", code.num_qubits());          // 7
println!("k = {}", code.num_logical_qubits());   // 1
println!("{}", code.code_parameters());           // [[7, 1]]

}


#[test]
fn test_user_guide_stabilizer_codes_rust_4() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::StabilizerCode;

let code = StabilizerCode::steane();
let logicals = code.logical_operators();

// [[7, 1]] code has 2k = 2 independent logical directions
assert_eq!(logicals.len(), 2);

for (i, op) in logicals.iter().enumerate() {
    println!("Logical {i}: {op}");
}
}


#[test]
fn test_user_guide_stabilizer_codes_rust_5() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::StabilizerCode;

let code = StabilizerCode::five_qubit();
assert_eq!(code.distance(), Some(3));

let code = StabilizerCode::steane();
assert_eq!(code.distance(), Some(3));

// Returns None if there are no logical qubits
let trivial = StabilizerCode::repetition(2);
// (still has distance for this case)
assert_eq!(trivial.distance(), Some(1));
}


#[test]
fn test_user_guide_stabilizer_codes_rust_6() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::StabilizerCode;

let code = StabilizerCode::repetition(3);

// X error on qubit 0: triggers first stabilizer (ZZI)
assert_eq!(code.syndrome(&X(0)), vec![true, false]);

// X error on qubit 1: triggers both (ZZI and IZZ)
assert_eq!(code.syndrome(&X(1)), vec![true, true]);

// Z error: commutes with all Z-stabilizers (undetectable)
assert_eq!(code.syndrome(&Z(0)), vec![false, false]);
}


#[test]
fn test_user_guide_stabilizer_codes_rust_7() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::StabilizerCode;

let toric = StabilizerCode::toric(2);
assert_eq!(toric.num_qubits(), 8);        // 2 * 2^2
assert_eq!(toric.num_logical_qubits(), 2);
assert_eq!(toric.distance(), Some(2));
}


#[test]
fn test_user_guide_stabilizer_codes_rust_8() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::StabilizerCode;
    use pecos_quantum::PauliStabilizerGroup;

// ZZ on qubits 0,1 -- but we declare 4 physical qubits
let group = PauliStabilizerGroup::new(vec![
    Zs([0, 1]),
]).unwrap();

let code = StabilizerCode::new(group, 4);

// k = n - rank = 4 - 1 = 3 logical qubits (not 1!)
assert_eq!(code.num_logical_qubits(), 3);
}


#[test]
fn test_user_guide_stabilizer_codes_rust_9() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::{PauliOperator, Xs, Zs};
    use pecos_qec::StabilizerCodeSpec;

// Build a 3-qubit bit-flip code with explicit logicals
let code = StabilizerCodeSpec::builder(3)
    .check(Zs([0, 1]))
    .check(Zs([1, 2]))
    .logical_z(Zs([0, 1, 2]))
    .logical_x(Xs([0, 1, 2]))
    .build()
    .unwrap();

// Full verification: checks all commutation relations
code.verify().unwrap();

assert_eq!(code.num_qubits(), 3);
assert_eq!(code.num_logical_qubits(), 1);
}


#[test]
fn test_user_guide_stabilizer_codes_rust_10() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::PauliOperator;
    use pecos_qec::{StabilizerCode, StabilizerCodeSpec};

let code = StabilizerCode::steane();
let spec = StabilizerCodeSpec::from_stabilizer_code(&code).unwrap();

// Logicals were discovered and paired
assert_eq!(spec.logical_xs().len(), 1);
assert_eq!(spec.logical_zs().len(), 1);

// Full verification passes
spec.verify().unwrap();
}


#[test]
fn test_user_guide_stabilizer_codes_rust_11() {
    use pecos_core::pauli::constructors::*;
    use pecos_core::{PauliOperator, Xs, Zs};
    use pecos_qec::{StabilizerCodeSpec, StabilizerFlipChecker};

let code = StabilizerCodeSpec::builder(7)
    .check(Xs([0, 2, 4, 6]))
    .check(Xs([1, 2, 5, 6]))
    .check(Xs([3, 4, 5, 6]))
    .check(Zs([0, 2, 4, 6]))
    .check(Zs([1, 2, 5, 6]))
    .check(Zs([3, 4, 5, 6]))
    .logical_z(Zs([0, 2, 4, 6]))
    .logical_x(Xs([0, 2, 4, 6]))
    .build()
    .unwrap();

// Check: can a weight-1 fault cause an undetectable logical error?
let checker = StabilizerFlipChecker::new(&code);
let analysis = checker.analyze_weight_with_types(1, true, true, true);
assert_eq!(analysis.undetectable_logical, 0);  // distance-3: safe against weight-1
}
