//! Auto-generated Rust tests from user-guide/gates.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py


use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_2() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    use pecos::prelude::*;

let mut sim = StdSparseStab::new(5);
let q: usize = 0;
let (q0, q1) = (0, 1);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_3() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.identity(q);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_4() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.x(q);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_5() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.y(q);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_6() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.z(q);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_7() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.h(q);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_8() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.h2(q);  // H2 variant
sim.h3(q);  // H3 variant
sim.h4(q);  // H4 variant
sim.h5(q);  // H5 variant
sim.h6(q);  // H6 variant
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_9() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.sx(q);
sim.sxdg(q);  // Adjoint (inverse)
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_10() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.sy(q);
sim.sydg(q);  // Adjoint (inverse)
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_11() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.sz(q);
sim.szdg(q);  // Adjoint (inverse): [[1, 0], [0, -i]]
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_12() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.f(q);
sim.fdg(q);  // Adjoint: X→Z, Y→X, Z→Y
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_13() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.f2(q);   sim.f2dg(q);
sim.f3(q);   sim.f3dg(q);
sim.f4(q);   sim.f4dg(q);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_14() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.cx(control, target);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_15() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.cy(control, target);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_16() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.cz(q1, q2);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_17() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.swap(q1, q2);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_18() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.iswap(q1, q2);
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_19() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.sxx(q1, q2);
sim.sxxdg(q1, q2);  // Adjoint
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_20() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.syy(q1, q2);
sim.syydg(q1, q2);  // Adjoint
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_21() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.szz(q1, q2);
sim.szzdg(q1, q2);  // Adjoint
    
}

use pecos::prelude::*;

#[test]
fn test_user_guide_gates_rust_22() {
    let mut sim = SparseStab::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let control: usize = 0;
    let target: usize = 1;
    sim.g(q1, q2);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_23() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    use pecos::prelude::*;
use std::f64::consts::PI;

let mut sim = StateVec::new(5);
let q: usize = 0;
let (q0, q1) = (0, 1);
let theta: f64 = PI / 4.0;
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_24() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.rx(theta, q);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_25() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.ry(theta, q);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_26() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.rz(theta, q);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_27() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.t(q);
sim.tdg(q);  // Adjoint (T†)
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_28() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.u(theta, phi, lam, q);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_29() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.r1xy(theta, phi, q);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_30() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.rxx(theta, q1, q2);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_31() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.ryy(theta, q1, q2);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_32() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.rzz(theta, q1, q2);
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_33() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    let result = sim.mz(q);
// result.outcome: true if |1⟩, false if |0⟩
// result.is_deterministic: true if already in eigenstate
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_34() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    let result = sim.mx(q);   // Measure +X
let result = sim.mnx(q);  // Measure -X
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_35() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    let result = sim.my(q);   // Measure +Y
let result = sim.mny(q);  // Measure -Y
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_36() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.pz(q);   // Prepare |0⟩ (eigenstate of +Z)
sim.pnz(q);  // Prepare |1⟩ (eigenstate of -Z)
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_37() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.px(q);   // Prepare |+⟩ = (|0⟩ + |1⟩)/√2
sim.pnx(q);  // Prepare |-⟩ = (|0⟩ - |1⟩)/√2
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_38() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.py(q);   // Prepare |+i⟩ = (|0⟩ + i|1⟩)/√2
sim.pny(q);  // Prepare |-i⟩ = (|0⟩ - i|1⟩)/√2
    
}

use pecos::prelude::*;
use std::f64::consts::PI;

#[test]
fn test_user_guide_gates_rust_39() {
    let mut sim = StateVec::new(5);
    let q: usize = 0;
    let q0: usize = 0;
    let q1: usize = 1;
    let q2: usize = 2;
    let theta: f64 = PI / 4.0;
    let phi: f64 = PI / 8.0;
    let lam: f64 = PI / 6.0;
    sim.mpz(q);   // Measure Z, prepare |0⟩
sim.mpnz(q);  // Measure -Z, prepare |1⟩
sim.mpx(q);   // Measure X, prepare |+⟩
sim.mpnx(q);  // Measure -X, prepare |-⟩
sim.mpy(q);   // Measure Y, prepare |+i⟩
sim.mpny(q);  // Measure -Y, prepare |-i⟩
    
}
