//! Auto-generated Rust tests from user-guide/wasm-foreign-objects.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py


use pecos::wasm::WasmForeignObject;
use std::fs;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    let wat = r#"(module
      (global $accumulator (mut i32) (i32.const 0))
      (func $init)
      (func $shot_reinit (i32.const 0) (global.set $accumulator))
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (func $mul (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.mul))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "shot_reinit" (func $shot_reinit))
      (export "add" (func $add))
      (export "mul" (func $mul))
      (export "memory" (memory 0))
    )"#;
    for name in &["math_functions.wasm", "math_functions.wat"] {
        fs::write(name, wat)?;
    }

    use pecos::wasm::WasmForeignObject;

// From a file path with default timeout (1 second)
let wasm = WasmForeignObject::new("math_functions.wasm")?;

// With custom timeout
let wasm = WasmForeignObject::with_timeout("math_functions.wasm", 5.0)?;

// With custom timeout and memory limit
let wasm = WasmForeignObject::with_limits(
    "math_functions.wasm",
    5.0,                      // timeout in seconds
    Some(10 * 1024 * 1024),   // memory limit in bytes
)?;
    
    Ok(())
}
    

use pecos::wasm::WasmForeignObject;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    let wasm_bytes: Vec<u8> = br#"(module
      (func $init)
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "add" (func $add))
      (export "memory" (memory 0))
    )"#.to_vec();

    use pecos::wasm::WasmForeignObject;

// From bytes with default timeout
let wasm = WasmForeignObject::from_bytes(&wasm_bytes)?;

// With custom timeout
let wasm = WasmForeignObject::from_bytes_with_timeout(&wasm_bytes, 5.0)?;

// With custom timeout and memory limit
let wasm = WasmForeignObject::from_bytes_with_limits(
    &wasm_bytes,
    5.0,
    Some(10 * 1024 * 1024),
)?;
    
    Ok(())
}
    

use pecos::wasm::{WasmForeignObject, ForeignObject};
use std::fs;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_3() -> Result<(), Box<dyn std::error::Error>> {
    let wat = r#"(module
      (func $init)
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (func $mul (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.mul))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "add" (func $add))
      (export "mul" (func $mul))
      (export "memory" (memory 0))
    )"#;
    fs::write("math.wasm", wat)?;

    use pecos::wasm::{WasmForeignObject, ForeignObject};

let mut wasm = WasmForeignObject::new("math.wasm")?;
wasm.init()?;

// Execute functions
let result = wasm.exec("add", &[5, 3])?;
println!("5 + 3 = {:?}", result);  // Output: 5 + 3 = [8]

// List available functions
println!("{:?}", wasm.get_funcs());
    
    Ok(())
}
    

use pecos::prelude::*;
use std::fs;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_4() -> Result<(), Box<dyn std::error::Error>> {
    let wat = r#"(module
      (func $init)
      (func $add (param i32 i32) (result i32) (local.get 0) (local.get 1) (i32.add))
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "add" (func $add))
      (export "memory" (memory 0))
    )"#;
    fs::write("math.wasm", wat)?;

    use pecos::prelude::*;

let qasm_code = r#"
    OPENQASM 2.0;
    include "qelib1.inc";

    qreg q[2];
    creg c[2];
    creg result[8];

    result = add(3, 5);

    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#;

// Build engine with WASM foreign functions
let results = qasm_engine()
    .qasm(qasm_code)
    .wasm("math.wasm")  // Load WASM module for foreign functions
    .to_sim()
    .run(100)?;
    
    Ok(())
}
    

use pecos::wasm::WasmForeignObject;
use std::fs;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_5() -> Result<(), Box<dyn std::error::Error>> {
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write("compute.wasm", wat)?;

    // 5 second timeout
let wasm = WasmForeignObject::with_timeout("compute.wasm", 5.0)?;
    
    Ok(())
}
    

use pecos::wasm::WasmForeignObject;
use std::fs;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_6() -> Result<(), Box<dyn std::error::Error>> {
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write("compute.wasm", wat)?;

    // Limit to 10 MB
let wasm = WasmForeignObject::with_limits(
    "compute.wasm",
    1.0,                      // timeout
    Some(10 * 1024 * 1024),   // memory limit
)?;

// No limit
let wasm = WasmForeignObject::with_limits("compute.wasm", 1.0, None)?;
    
    Ok(())
}
    

use pecos::wasm::WasmForeignObject;
use std::fs;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_7() -> Result<(), Box<dyn std::error::Error>> {
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write("math.wat", wat)?;

    let wasm = WasmForeignObject::new("math.wat")?;

// Get the WASM bytes
let bytes = wasm.wasm_bytes();

// Create a new instance from bytes
let wasm2 = WasmForeignObject::from_bytes(bytes)?;
    
    Ok(())
}
    

use pecos::wasm::WasmForeignObject;
use std::fs;

#[test]
fn test_user_guide_wasm_foreign_objects_rust_8() -> Result<(), Box<dyn std::error::Error>> {
    let wat = r#"(module
      (func $init)
      (memory (;0;) 1)
      (export "init" (func $init))
      (export "memory" (memory 0))
    )"#;
    fs::write("math.wat", wat)?;

    use pecos::wasm::WasmForeignObject;

// File not found error - this intentionally fails
match WasmForeignObject::new("nonexistent.wasm") {
    Err(e) => println!("Expected error: {}", e),
    Ok(_) => println!("Unexpected success"),
}
    
    Ok(())
}
    
