//! Auto-generated Rust tests from user-guide/getting-started.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_getting_started_rust_1() {
    use pecos::prelude::*;
    let sim = SparseStab::new(1);
    println!("PECOS is working! Created a {}-qubit simulator", sim.num_qubits());
}



#[test]
fn test_user_guide_getting_started_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos_hugr::hugr_sim;
    use std::path::PathBuf;
    let mut hugr_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    hugr_path.push("../../../../../crates/pecos/tests/test_data/hugr/bell_state.hugr");


// Load and run a pre-compiled HUGR circuit
let results = hugr_sim(&hugr_path)
    .seed(42)
    .run(10)?;

println!("Got {} shots", results.shots.len());

    Ok(())
}

