//! Auto-generated Rust tests from user-guide/graph-api.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_graph_api_rust_1() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;

let mut graph = Graph::new();
let n0 = graph.add_node();
let n1 = graph.add_node();
let n2 = graph.add_node();
let n3 = graph.add_node();
graph.add_edge(n0, n1);
graph.add_edge(n1, n2);
graph.add_edge(n0, n2);
graph.add_edge(n2, n3);

graph.set_weight(n0, n1, 1.0);
graph.set_weight(n1, n2, 2.0);
graph.set_weight(n0, n2, 5.0);

let source_node = n0;

}


#[test]
fn test_user_guide_graph_api_rust_2() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
// Or: use pecos_num::graph::{Graph, Attribute};

// Create graph and nodes
let mut graph = Graph::new();
let n0 = graph.add_node();
let n1 = graph.add_node();

// Add edge with attributes
graph.add_edge(n0, n1);
graph.set_weight(n0, n1, 5.0);

if let Some(attrs) = graph.edge_attrs_mut(n0, n1) {
    attrs.insert("label".to_string(),
                Attribute::String("boundary".into()));
    attrs.insert("path".to_string(),
                Attribute::IntList(vec![1, 2, 3]));
}

}


#[test]
fn test_user_guide_graph_api_rust_3() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;

let mut graph = Graph::new();
// Or with initial capacity
let mut graph = Graph::with_capacity(100, 200);  // nodes, edges

}


#[test]
fn test_user_guide_graph_api_rust_4() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Access graph-level attributes (always available)
let attrs = graph.attrs_mut();

// Individual insert
attrs.insert("name".to_string(),
            Attribute::String("surface_code".into()));
attrs.insert("distance".to_string(),
            Attribute::Int(5));

// Batch extend
attrs.extend([
    ("version".to_string(), Attribute::String("1.0".into())),
    ("author".to_string(), Attribute::String("Alice".into())),
    ("date".to_string(), Attribute::String("2025-01-26".into())),
]);

}


#[test]
fn test_user_guide_graph_api_rust_5() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    let attrs = graph.attrs();

// Get attribute
if let Some(name) = attrs.get("name") {
    println!("{:?}", name);
}

// Check existence
if attrs.contains_key("distance") {
    println!("{:?}", attrs["distance"]);
}

}


#[test]
fn test_user_guide_graph_api_rust_6() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    let n0 = graph.add_node();  // Returns node ID (usize)
let n1 = graph.add_node();

}


#[test]
fn test_user_guide_graph_api_rust_7() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Count nodes
let count = graph.node_count();

// Iterate over nodes
for node in graph.nodes() {
    println!("{}", node);
}

}


#[test]
fn test_user_guide_graph_api_rust_8() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Create nodes
let n0 = graph.add_node();
let n1 = graph.add_node();

// Access node attributes
if let Some(attrs) = graph.node_attrs_mut(n0) {
    // Individual insert
    attrs.insert("label".to_string(),
                Attribute::String("qubit_0".into()));
    attrs.insert("position".to_string(),
                Attribute::Json(json!([0.0, 1.0, 2.0])));

    // Batch extend
    attrs.extend([
        ("x".to_string(), Attribute::Float(1.0)),
        ("y".to_string(), Attribute::Float(2.0)),
    ]);
}

}


#[test]
fn test_user_guide_graph_api_rust_9() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    if let Some(attrs) = graph.node_attrs(n0) {
    // Get attribute
    if let Some(label) = attrs.get("label") {
        println!("{:?}", label);
    }

    // Check existence
    if attrs.contains_key("label") {
        println!("{:?}", attrs["label"]);
    }
}

}


#[test]
fn test_user_guide_graph_api_rust_10() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Add edge
graph.add_edge(n0, n1);

// Add edge with weight
graph.add_edge(n0, n1);
graph.set_weight(n0, n1, 5.0);

}


#[test]
fn test_user_guide_graph_api_rust_11() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;

graph.add_edge(n0, n1);
graph.set_weight(n0, n1, 5.0);

// BTreeMap mutable access
if let Some(attrs) = graph.edge_attrs_mut(n0, n1) {
    // Individual insert
    attrs.insert("label".to_string(),
                Attribute::String("boundary".into()));
    attrs.insert("syn_path".to_string(),
                Attribute::IntList(vec![1, 2, 3]));

    // Batch extend (from Extend trait)
    attrs.extend([
        ("key1".to_string(), Attribute::Int(42)),
        ("key2".to_string(), Attribute::String("value".into())),
    ]);
}

}


#[test]
fn test_user_guide_graph_api_rust_12() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Get weight
let weight = graph.get_weight(n0, n1);  // Returns Option<f64>

// Get all edge data
let data = graph.get_edge_data(n0, n1);  // Returns Option<BTreeMap>

// Access individual attributes
if let Some(attrs) = graph.edge_attrs(n0, n1) {
    let label = attrs.get("label");  // Returns Option<&Attribute>

    // Check if attribute exists
    if attrs.contains_key("label") {
        println!("{:?}", attrs["label"]);
    }
}

}


#[test]
fn test_user_guide_graph_api_rust_13() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Find edge ID from node pair
if let Some(edge_id) = graph.find_edge(n0, n1) {
    // Get endpoints from edge ID
    if let Some((a, b)) = graph.edge_endpoints(edge_id) {
        println!("Edge {}: {} -> {}", edge_id, a, b);
    }
}

}


#[test]
fn test_user_guide_graph_api_rust_14() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Count edges
let count = graph.edge_count();

// Iterate over edges (returns (node_a, node_b, weight) tuples)
for (a, b, weight) in graph.edges() {
    println!("Edge {}-{}: weight={}", a, b, weight);
}

}


#[test]
fn test_user_guide_graph_api_rust_15() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;

let mut graph = Graph::new();
let n0 = graph.add_node();
let n1 = graph.add_node();
graph.add_edge(n0, n1);

// Native types (fast path)
if let Some(attrs) = graph.edge_attrs_mut(n0, n1) {
    attrs.insert("label".into(), Attribute::String("control".into()));
    attrs.insert("weight_factor".into(), Attribute::Float(2.5));
    attrs.insert("enabled".into(), Attribute::Bool(true));
    attrs.insert("path".into(), Attribute::IntList(vec![1, 2, 3]));
}

// Complex types (JSON variant)
if let Some(attrs) = graph.node_attrs_mut(5) {
    attrs.insert("metadata".into(), Attribute::Json(json!({
        "type": "data_qubit",
        "coordinates": [0.5, 1.2],
        "neighbors": [4, 6, 8]
    })));
}

// Nested structures
graph.attrs_mut().insert("config".into(), Attribute::Json(json!({
    "version": "2.0",
    "parameters": {
        "threshold": 0.01,
        "rounds": [10, 20, 30],
        "enabled": true
    }
})));

}


#[test]
fn test_user_guide_graph_api_rust_16() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Find maximum weight perfect matching
let matching = graph.max_weight_matching(true);

// matching is a BTreeMap<usize, usize>
for (node, matched) in &matching {
    println!("{} matched with {}", node, matched);
}

}


#[test]
fn test_user_guide_graph_api_rust_17() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Get shortest path distances - faster if you don't need paths
let distances = graph.shortest_path_distances(source_node);

// distances is a BTreeMap<usize, f64>
for (node, dist) in &distances {
    println!("Distance to {}: {}", node, dist);
}

}


#[test]
fn test_user_guide_graph_api_rust_18() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Get shortest paths with full path reconstruction
let paths = graph.single_source_shortest_path(source_node);

// paths is a BTreeMap<usize, Vec<usize>>
for (node, path) in &paths {
    println!("Path to {}: {:?}", node, path);
}

}


#[test]
fn test_user_guide_graph_api_rust_19() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;
    // Create subgraph from node subset
let nodes_to_keep = vec![0, 2, 5, 7];
let subgraph = graph.subgraph(&nodes_to_keep);

}


#[test]
fn test_user_guide_graph_api_rust_20() {
    use pecos::graph::{Attribute, Graph};
    use serde_json::json;
    let mut graph = Graph::new();
    let n0 = graph.add_node();
    let n1 = graph.add_node();
    let n2 = graph.add_node();
    let n3 = graph.add_node();
    graph.add_edge(n0, n1);
    graph.add_edge(n1, n2);
    graph.add_edge(n0, n2);
    graph.add_edge(n2, n3);
    graph.set_weight(n0, n1, 1.0);
    graph.set_weight(n1, n2, 2.0);
    graph.set_weight(n0, n2, 5.0);
    let source_node = n0;

// Build a simple graph
let mut graph = Graph::new();
let n0 = graph.add_node();
let n1 = graph.add_node();
let n2 = graph.add_node();

// Add edges with weights
graph.add_edge(n0, n1);
graph.set_weight(n0, n1, 1.0);

graph.add_edge(n1, n2);
graph.set_weight(n1, n2, 2.0);

graph.add_edge(n0, n2);
graph.set_weight(n0, n2, 5.0);

// Add edge attributes
if let Some(attrs) = graph.edge_attrs_mut(n0, n1) {
    attrs.extend([
        ("label".to_string(), Attribute::String("virtual".into())),
        ("path".to_string(), Attribute::IntList(vec![0, 1])),
        ("active".to_string(), Attribute::Bool(true)),
    ]);
}

// Find shortest paths
let paths = graph.single_source_shortest_path(n0);
println!("Path n0->n2: {:?}", paths.get(&n2));  // Some([0, 1, 2])

// Find matching
let matching = graph.max_weight_matching(true);
println!("Matching: {:?}", matching);

}
