//! Auto-generated Rust tests from user-guide/stabilizer-codes.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py


use pecos_qec::StabilizerCode;
use pecos_core::pauli::constructors::*;

// 3-qubit bit-flip repetition code: generators ZZI, IZZ

#[test]
fn test_user_guide_stabilizer_codes_rust_2() {
    let group = pecos_quantum::PauliStabilizerGroup::new(vec![
        Zs([0, 1]),
        Zs([1, 2]),
    ]).unwrap();

    let code = StabilizerCode::from_group(group);

    // Or use the built-in constructor:
    let code = StabilizerCode::repetition(3);
}

use pecos_qec::StabilizerCode;


#[test]
fn test_user_guide_stabilizer_codes_rust_3() {
    let code = StabilizerCode::steane();

    println!("n = {}", code.num_qubits());          // 7
    println!("k = {}", code.num_logical_qubits());   // 1
    println!("{}", code.code_parameters());           // [[7, 1]]
}

use pecos_qec::StabilizerCode;


#[test]
fn test_user_guide_stabilizer_codes_rust_4() {
    let code = StabilizerCode::steane();
    let logicals = code.logical_operators();

    // [[7, 1]] code has 2k = 2 independent logical directions
    assert_eq!(logicals.len(), 2);

    for (i, op) in logicals.iter().enumerate() {
        println!("Logical {i}: {op}");
    }
}

use pecos_qec::StabilizerCode;


#[test]
fn test_user_guide_stabilizer_codes_rust_5() {
    let code = StabilizerCode::five_qubit();
    assert_eq!(code.distance(), Some(3));

    let code = StabilizerCode::steane();
    assert_eq!(code.distance(), Some(3));

    // Returns None if there are no logical qubits
    let trivial = StabilizerCode::repetition(2);
    // (still has distance for this case)
    assert_eq!(trivial.distance(), Some(1));
}

use pecos_qec::StabilizerCode;
use pecos_core::pauli::constructors::*;


#[test]
fn test_user_guide_stabilizer_codes_rust_6() {
    let code = StabilizerCode::repetition(3);

    // X error on qubit 0: triggers first stabilizer (ZZI)
    assert_eq!(code.syndrome(&X(0)), vec![true, false]);

    // X error on qubit 1: triggers both (ZZI and IZZ)
    assert_eq!(code.syndrome(&X(1)), vec![true, true]);

    // Z error: commutes with all Z-stabilizers (undetectable)
    assert_eq!(code.syndrome(&Z(0)), vec![false, false]);
}

use pecos_qec::StabilizerCode;


#[test]
fn test_user_guide_stabilizer_codes_rust_7() {
    let toric = StabilizerCode::toric(3);
    assert_eq!(toric.num_qubits(), 18);       // 2 * 3^2
    assert_eq!(toric.num_logical_qubits(), 2);
    assert_eq!(toric.distance(), Some(3));
}

use pecos_qec::StabilizerCode;
use pecos_quantum::PauliStabilizerGroup;
use pecos_core::pauli::constructors::Zs;

// ZZ on qubits 0,1 -- but we declare 4 physical qubits

#[test]
fn test_user_guide_stabilizer_codes_rust_8() {
    let group = PauliStabilizerGroup::new(vec![
        Zs([0, 1]),
    ]).unwrap();

    let code = StabilizerCode::new(group, 4);

    // k = n - rank = 4 - 1 = 3 logical qubits (not 1!)
    assert_eq!(code.num_logical_qubits(), 3);
}

use pecos_qec::StabilizerCodeSpec;
use pecos_core::{Xs, Zs};

// Build a 3-qubit bit-flip code with explicit logicals

#[test]
fn test_user_guide_stabilizer_codes_rust_9() {
    let code = StabilizerCodeSpec::builder(3)
        .check(Zs([0, 1]))
        .check(Zs([1, 2]))
        .logical_z(Zs([0, 1, 2]))
        .logical_x(Xs([0, 1, 2]))
        .build()
        .unwrap();

    // Full verification: checks all commutation relations
    code.verify().unwrap();

    assert_eq!(code.num_qubits(), 3);
    assert_eq!(code.num_logical_qubits(), 1);
}

use pecos_qec::{StabilizerCode, StabilizerCodeSpec};


#[test]
fn test_user_guide_stabilizer_codes_rust_10() {
    let code = StabilizerCode::steane();
    let spec = StabilizerCodeSpec::from_stabilizer_code(&code).unwrap();

    // Logicals were discovered and paired
    assert_eq!(spec.logical_xs().len(), 1);
    assert_eq!(spec.logical_zs().len(), 1);

    // Full verification passes
    spec.verify().unwrap();
}

use pecos_qec::{StabilizerCodeSpec, StabilizerFlipChecker};
use pecos_core::{Xs, Zs};


#[test]
fn test_user_guide_stabilizer_codes_rust_11() -> Result<(), Box<dyn std::error::Error>> {
    let code = StabilizerCodeSpec::builder(7)
        .check(Xs([0, 2, 4, 6]))
        .check(Xs([1, 2, 5, 6]))
        .check(Xs([3, 4, 5, 6]))
        .check(Zs([0, 2, 4, 6]))
        .check(Zs([1, 2, 5, 6]))
        .check(Zs([3, 4, 5, 6]))
        .logical_z(Zs([0, 2, 4, 6]))
        .logical_x(Xs([0, 2, 4, 6]))
        .build()
        .unwrap();

    // Check: can a weight-1 fault cause an undetectable logical error?
    let checker = StabilizerFlipChecker::new(&code);
    let analysis = checker.analyze_weight_with_types(1, true, true, true);
    assert_eq!(analysis.undetectable_logical, 0);  // distance-3: safe against weight-1
    Ok(())
}
