//! Auto-generated Rust tests from user-guide/hugr-simulation.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]


#[test]
fn test_user_guide_hugr_simulation_rust_1() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;

let program = Qasm::from_string(r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#);

let results = sim(program).seed(42).shots(1000).run()?;
println!("Results: {:?}", results);

    Ok(())
}



#[test]
fn test_user_guide_hugr_simulation_rust_2() -> Result<(), Box<dyn std::error::Error>> {
    use pecos::prelude::*;

let program = Qasm::from_string(r#"
    OPENQASM 2.0;
    include "qelib1.inc";
    qreg q[2];
    creg c[2];
    h q[0];
    cx q[0], q[1];
    measure q -> c;
"#);

let mut experiment = sim(program).seed(42).build()?;
let results = experiment.run(1000)?;
println!("Results: {:?}", results);

    Ok(())
}

