//! Auto-generated Rust tests from user-guide/runtime-custom-events.md
//! DO NOT EDIT - Generated by scripts/docs/generate_doc_tests.py
#![allow(unused_imports, unused_variables, unused_mut, unused_assignments, dead_code, non_snake_case)]



#[test]
fn test_user_guide_runtime_custom_events_rust_1() {
    use pecos_qis::{
RuntimeCustomEventDisposition, RuntimeCustomEventPolicy, SeleneRuntime,
};
    let mut runtime = SeleneRuntime::new("example-runtime.so");
    runtime.set_custom_event_policy(RuntimeCustomEventPolicy::RejectUnhandled);
    runtime.set_custom_event_handler(|event| {
        // Invented metadata protocol: tag 7301, version byte 1, no physical effect.
        Ok(if event.tag == 7301 && event.data == [1] {
            RuntimeCustomEventDisposition::MetadataOnly
        } else {
            RuntimeCustomEventDisposition::Unsupported
        })
    });
}
