repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/reference/_autosummary/
      - id: end-of-file-fixer
        exclude: ^docs/reference/_autosummary/
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      # Python-specific
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/crate-ci/typos
    rev: v1.20.10
    hooks:
      - id: typos
        args: []
        exclude: |
            (?x)^(
                python/pecos/simulators/cuquantum_old/.*|
            )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        exclude: |
            (?x)^(
                python/pecos/simulators/cuquantum_old/custatevec/bindings.py|
            )$

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
    -   id: blackdoc
        additional_dependencies:
        - black==24.1.1
