# Define rules, plugins, and configurations for the ruff linter.
# For more details on rules see: https://docs.astral.sh/ruff/rules

target-version = "py39"
line-length = 120
extend-exclude = ["python/pecos/simulators/cuquantum/*"]
select = [
    "ASYNC",    # flake8-async
    "B",        # flake8-bugbear
    "BLE",      # flake8-blind-except
    "C4",       # flake8-comprehensions
    "COM",      # flake8-commas
    "DTZ",      # flake8-datetimez
    "E",        # pycodestyle
    "EM",       # flake8-errmsg
    "EXE",      # flake8-executable
    "F",        # Pyflakes
    "FA",       # flake8-future-annotations
    "FBT001",   # flake8-boolean-trap
    "FLY",      # flynt
    "G",        # flake8-logging-format
    "I",        # isort (imports)
    "ICN",      # flake8-import-conventions
    "INP",      # flake8-no-pep420 (namespace/no __init__.py)
    "INT",      # flake8-gettext
    "ISC",      # flake9-implicit-str-concat
    "N",        # pep8-naming
    "PIE",      # flake8-pie
    "PL",       # Pylint
    "PT",       # flake8-pytest-style
    "PTH",      # flake8-use-pathlib
    "PYI",      # flake8-pyi
    "Q",        # flake8-quotes (prefer double quotes over single)
    "RSE",      # flake8-raise
    "RUF",      # Ruff-specific rules
    "SIM",      # flake8-simplify
    "SLOT",     # flake8-slots
    "T10",      # flake8-debugger
    "TCH",      # flake8-type-checking
    "TD",       # flake8-todos
    "TID",      # flake8-tidy-imports
    "TRY",      # tryceratops
    "UP",       # pyupgrade (upgrade syntax from old to new)
    "W",        # pycodestyle
    "YTT",      # flake8-2020

    # TODO: uncomment to deal with shadowing builtins
    # "A",        # flake8-builtins
    # TODO: uncomment to improve type annotations
    # "ANN",      # flake8-annotations
    # TODO: uncomment to deal with unused arguments
    # "ARG",      # flake8-unused-arguments
    # TODO: uncomment to improve documentation
    # "D",        # flake8-docstrings
    # "D4",
    # TODO: uncomment to erase commented code
    # "ERA",      # eradicate
    # "FBT",      # flake8-boolean-trap
    # TODO: uncomment to alert about TODOs to fix
    # "FIX",      # flak8-fixme
    # TODO: uncomment to improve performance
    # "PERF",     # Perflint
    # TODO: uncomment to clean up returns
    # "RET",      # flake8-return
    # "S",        # flake8-bandit
    # "SLF",      # flake8-self
    # TODO: uncomment to highlight print statements
    # "T20",      # flake8-print (any print statement)
]

ignore = [
    # pydocstyle: http://www.pydocstyle.org/en/stable/error_codes.html
    # TODO: Remove errors below to further improve docstring linting
    "D107", # Missing docstring in __init__
    # "D212", # Multi-line docstring summary should start at the first line
    # "D401", # First line of docstring should be in imperative mood: "{first_line}"
    "D105", # Missing docstring in magic method
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package

    # flake8-simplify
    "SIM102", # Use a single `if` statement instead of nested `if` statements
    "SIM108", # Use ternary operator

    # ruff
    "RUF010", # f-string type-conversion

    # flake8-todos
    "TD002", # Missing author in TODO
    "TD003", # Missing issue link on the line following this TODO

    # tryceratops
    "TRY003", # Avoid specifying long messages outside the exception class
    # TODO: Remove to improve error handling...
    "TRY002", # Custom exceptions

    # flak8-pyi
    "PYI009", # Empty body should contain ..., not pass
    "PYI010", # purely ... function stub
    "PYI013", # Non-empty class body must not contain ...

    # pylint
    "PLW2901", # Loop variable overwritten
    "PLR0911", # Too many returns
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments
    "PLR0915", # Too many statements
    "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
    "PLR5501", # Combining else and if

    # pep8-names
    "N802",  # Function name should be lowercase
]

[pycodestyle]
max-doc-length = 120

[pydocstyle]
convention = "google"

[isort]
split-on-trailing-comma = true

[flake8-tidy-imports]
ban-relative-imports = "all"

[flake8-type-checking]
strict = true

[per-file-ignores]
"docs/**/*.py" = ["INP001", "E402"]
"python/**/__init__.py" = ["F401"]
"python/pecos/circuits/qasm/std_gates.py" = ["F401"]
"python/pecos/engines/hybrid_engine_multiprocessing.py" = ["BLE001"]
"python/pecos/reps/pypmir/types.py" = ["F401"]
"tests/**/*.py" = ["INP001", "ANN", "FBT001"] # ["D100", "D103", "B018", "FBT001"]
# TODO: comment to work on better typing
"python/pecos/circuit_converters/**/*.py" = ["ANN"]
"python/pecos/circuits/**/*.py" = ["ANN"]
"python/pecos/decoders/**/*.py" = ["ANN"]
"python/pecos/engines/**/*.py" = ["ANN"]
"python/pecos/error_models/**/*.py" = ["ANN"]
"python/pecos/misc/**/*.py" = ["ANN"]
"python/pecos/qeccs/**/*.py" = ["ANN"]
"python/pecos/simulators/**/*.py" = ["ANN"]
"python/pecos/tools/*.py" = ["ANN"]
