//! End-to-end execution tests for HUGR programs.
//!
//! Load `.hugr` files generated by Guppy, parse to PHIR via `parse_hugr_bytes_to_phir`,
//! run through `PhirEngine` + `SimBuilder`, and verify measurement results.

#![cfg(feature = "runtime")]

use pecos::prelude::*;

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/// Parse HUGR bytes, build a `PhirEngine`, run through `SimBuilder`, and return
/// the "c" register values for each shot.
fn run_hugr(hugr_bytes: &[u8], seed: u64, shots: usize) -> Vec<u32> {
    let builder = pecos_phir::phir_engine()
        .from_hugr_bytes(hugr_bytes)
        .expect("HUGR -> PhirEngineBuilder");

    let results = sim_builder()
        .classical(builder)
        .seed(seed)
        .run(shots)
        .expect("SimBuilder run should succeed");

    results
        .shots
        .iter()
        .filter_map(|shot| shot.data.get("c").and_then(Data::as_u32))
        .collect()
}

// ---------------------------------------------------------------------------
// Deterministic circuits
// ---------------------------------------------------------------------------

#[test]
fn hugr_single_hadamard_runs() {
    // H on |0> then measure: 50/50, but should produce valid results
    let bytes = include_bytes!("test_data/hugr/single_hadamard.hugr");
    let results = run_hugr(bytes, 42, 100);
    assert_eq!(results.len(), 100, "should get 100 shot results");
    // Every result should be 0 or 1 (single qubit measurement)
    for &v in &results {
        assert!(
            v == 0 || v == 1,
            "single qubit measurement should be 0 or 1, got {v}"
        );
    }
}

#[test]
fn hugr_bell_state_correlations() {
    // Bell state: H on q0, CX(q0, q1), measure both.
    // Outcomes are correlated: only 00 (0) or 11 (3).
    let bytes = include_bytes!("test_data/hugr/bell_state.hugr");
    let results = run_hugr(bytes, 42, 200);
    assert_eq!(results.len(), 200);
    for &v in &results {
        assert!(
            v == 0 || v == 3,
            "Bell state should only produce 00 or 11, got {v}"
        );
    }
    // Should have at least some of each outcome over 200 shots
    let count_0 = results.iter().filter(|&&v| v == 0).count();
    let count_3 = results.iter().filter(|&&v| v == 3).count();
    assert!(count_0 > 0, "Bell state should sometimes produce 00");
    assert!(count_3 > 0, "Bell state should sometimes produce 11");
}

#[test]
fn hugr_ghz_state_correlations() {
    // GHZ state: H on q0, CX(q0,q1), CX(q1,q2), measure all 3.
    // Outcomes: only 000 (0) or 111 (7).
    let bytes = include_bytes!("test_data/hugr/ghz_state.hugr");
    let results = run_hugr(bytes, 42, 200);
    assert_eq!(results.len(), 200);
    for &v in &results {
        assert!(
            v == 0 || v == 7,
            "GHZ state should only produce 000 or 111, got {v}"
        );
    }
}

#[test]
fn hugr_rz_x_deterministic() {
    // Rz(pi) on q0 (stays |0>), X on q1 (flips to |1>).
    // q0 measures 0, q1 measures 1 -> result = 0b10 = 2
    // Rz(pi) simplifies to Z (Clifford), so default stabilizer backend works.
    let bytes = include_bytes!("test_data/hugr/rz_x.hugr");
    let results = run_hugr(bytes, 42, 20);
    assert_eq!(results.len(), 20);
    for &v in &results {
        assert_eq!(v, 2, "Rz(pi)|0> + X|0> should give 0b10 = 2, got {v}");
    }
}

// ---------------------------------------------------------------------------
// Cross-engine: HUGR vs QASM for equivalent circuits
// ---------------------------------------------------------------------------

/// Run a QASM program through `QasmEngine` for comparison.
fn run_qasm(qasm: &str, seed: u64, shots: usize) -> Vec<u32> {
    let results = sim_builder()
        .classical(qasm_engine().qasm(qasm))
        .seed(seed)
        .run(shots)
        .expect("QasmEngine run should succeed");

    results
        .shots
        .iter()
        .filter_map(|shot| shot.data.get("c").and_then(Data::as_u32))
        .collect()
}

#[test]
fn hugr_vs_qasm_bell_state() {
    let bell_qasm = r#"
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
h q[0];
cx q[0], q[1];
measure q -> c;
"#;
    let hugr_bytes = include_bytes!("test_data/hugr/bell_state.hugr");

    let qasm_results = run_qasm(bell_qasm, 42, 100);
    let hugr_results = run_hugr(hugr_bytes, 42, 100);

    // Both should produce valid Bell state outcomes
    for &v in &qasm_results {
        assert!(v == 0 || v == 3);
    }
    for &v in &hugr_results {
        assert!(v == 0 || v == 3);
    }
}
