OPENQASM 2.0;
include "hqslib1.inc";
barrier ;
reset q_test[0];
reset q_test[1];
reset q_test[2];
reset q_test[3];
reset q_test[4];
reset q_test[5];
reset q_test[6];
reset a_test[0];
barrier q_test;
h q_test[0];
h q_test[4];
h q_test[6];
cx q_test[4], q_test[5];
cx q_test[0], q_test[1];
cx q_test[6], q_test[3];
cx q_test[4], q_test[2];
cx q_test[6], q_test[5];
cx q_test[0], q_test[3];
cx q_test[4], q_test[1];
cx q_test[3], q_test[2];
barrier ;
// verification step
cx q_test[5], a_test[0];
cx q_test[1], a_test[0];
cx q_test[3], a_test[0];
measure a_test[0] -> init_test[0];
// Repeat 2 times (unrolled)
barrier ;
if(init_test[0] == 1) reset q_test[0];
if(init_test[0] == 1) reset q_test[1];
if(init_test[0] == 1) reset q_test[2];
if(init_test[0] == 1) reset q_test[3];
if(init_test[0] == 1) reset q_test[4];
if(init_test[0] == 1) reset q_test[5];
if(init_test[0] == 1) reset q_test[6];
if(init_test[0] == 1) reset a_test[0];
barrier q_test;
if(init_test[0] == 1) h q_test[0];
if(init_test[0] == 1) h q_test[4];
if(init_test[0] == 1) h q_test[6];
if(init_test[0] == 1) cx q_test[4], q_test[5];
if(init_test[0] == 1) cx q_test[0], q_test[1];
if(init_test[0] == 1) cx q_test[6], q_test[3];
if(init_test[0] == 1) cx q_test[4], q_test[2];
if(init_test[0] == 1) cx q_test[6], q_test[5];
if(init_test[0] == 1) cx q_test[0], q_test[3];
if(init_test[0] == 1) cx q_test[4], q_test[1];
if(init_test[0] == 1) cx q_test[3], q_test[2];
barrier ;
// verification step
if(init_test[0] == 1) cx q_test[5], a_test[0];
if(init_test[0] == 1) cx q_test[1], a_test[0];
if(init_test[0] == 1) cx q_test[3], a_test[0];
if(init_test[0] == 1) measure a_test[0] -> init_test[0];
barrier ;
if(init_test[0] == 1) reset q_test[0];
if(init_test[0] == 1) reset q_test[1];
if(init_test[0] == 1) reset q_test[2];
if(init_test[0] == 1) reset q_test[3];
if(init_test[0] == 1) reset q_test[4];
if(init_test[0] == 1) reset q_test[5];
if(init_test[0] == 1) reset q_test[6];
if(init_test[0] == 1) reset a_test[0];
barrier q_test;
if(init_test[0] == 1) h q_test[0];
if(init_test[0] == 1) h q_test[4];
if(init_test[0] == 1) h q_test[6];
if(init_test[0] == 1) cx q_test[4], q_test[5];
if(init_test[0] == 1) cx q_test[0], q_test[1];
if(init_test[0] == 1) cx q_test[6], q_test[3];
if(init_test[0] == 1) cx q_test[4], q_test[2];
if(init_test[0] == 1) cx q_test[6], q_test[5];
if(init_test[0] == 1) cx q_test[0], q_test[3];
if(init_test[0] == 1) cx q_test[4], q_test[1];
if(init_test[0] == 1) cx q_test[3], q_test[2];
barrier ;
// verification step
if(init_test[0] == 1) cx q_test[5], a_test[0];
if(init_test[0] == 1) cx q_test[1], a_test[0];
if(init_test[0] == 1) cx q_test[3], a_test[0];
if(init_test[0] == 1) measure a_test[0] -> init_test[0];
// Logical X
x q_test[4];
x q_test[5];
x q_test[6];
