/*!
Test that PhirEngine can execute PHIR modules generated by the improved converter
with explicit bit-combining operations.
*/

use pecos_core::errors::PecosError;
use pecos_engines::{Engine, ClassicalEngine};
use pecos_engines::hybrid::builder::HybridEngineBuilder;
use pecos_engines::quantum::StateVecEngine;
use pecos_engines::shot_results::Data;
use pecos_phir_json::phir_json_to_module;
use pecos_phir::PhirEngine;
use std::collections::BTreeMap;

#[test]
fn test_bell_state_with_improved_converter() -> Result<(), PecosError> {
    let bell_json = r#"{
        "format": "PHIR/JSON",
        "version": "0.1.0",
        "metadata": {"description": "Bell state"},
        "ops": [
            {"data": "qvar_define", "data_type": "qubits", "variable": "q", "size": 2},
            {"data": "cvar_define", "data_type": "i64", "variable": "m", "size": 2},
            {"qop": "H", "args": [["q", 0]]},
            {"qop": "CX", "args": [["q", 0], ["q", 1]]},
            {"qop": "Measure", "args": [["q", 0]], "returns": [["m", 0]]},
            {"qop": "Measure", "args": [["q", 1]], "returns": [["m", 1]]},
            {"cop": "Result", "args": ["m"], "returns": ["c"]}
        ]
    }"#;

    // Use the improved converter
    let module = phir_json_to_module(bell_json)?;

    // Create PhirEngine with the improved module
    let engine = PhirEngine::new(module)
        .map_err(|e| PecosError::Input(format!("Failed to create PhirEngine: {}", e)))?;

    let num_qubits = engine.num_qubits();
    let quantum_engine = Box::new(StateVecEngine::new(num_qubits));

    let mut hybrid_engine = HybridEngineBuilder::new()
        .with_classical_engine(Box::new(engine))
        .with_quantum_engine(quantum_engine)
        .build();

    // Run multiple shots to verify Bell state behavior
    let mut counts: BTreeMap<u32, usize> = BTreeMap::new();

    for i in 0..1 {  // Changed to just 1 shot for debugging
        eprintln!("=== Running shot {} ===", i);
        let shot = hybrid_engine.run_shot()?;
        eprintln!("Shot result: {:?}", shot.data);

        if let Some(Data::U32(value)) = shot.data.get("c") {
            *counts.entry(*value).or_insert(0) += 1;
        } else {
            eprintln!("WARNING: No 'c' key in shot data!");
        }

        Engine::reset(&mut hybrid_engine)?;
    }

    // Verify we got valid Bell state results
    println!("Bell state results with improved converter:");
    for (value, count) in &counts {
        println!("  |{:02b}⟩: {}", value, count);
    }

    // Should only get 00 (0) or 11 (3)
    assert!(counts.len() <= 2, "Should have at most 2 outcomes");
    assert!(counts.contains_key(&0) || counts.contains_key(&3), "Should produce |00⟩ or |11⟩");

    // Check no intermediate values
    for &value in counts.keys() {
        assert!(value == 0 || value == 3, "Should only produce 0 or 3, got {}", value);
    }

    Ok(())
}

#[test]
fn test_three_bit_measurement_with_improved_converter() -> Result<(), PecosError> {
    let json = r#"{
        "format": "PHIR/JSON",
        "version": "0.1.0",
        "metadata": {"description": "Three bit measurement"},
        "ops": [
            {"data": "qvar_define", "data_type": "qubits", "variable": "q", "size": 3},
            {"data": "cvar_define", "data_type": "u32", "variable": "m", "size": 3},
            {"qop": "H", "args": [["q", 0]]},
            {"qop": "H", "args": [["q", 1]]},
            {"qop": "H", "args": [["q", 2]]},
            {"qop": "Measure", "args": [["q", 0]], "returns": [["m", 0]]},
            {"qop": "Measure", "args": [["q", 1]], "returns": [["m", 1]]},
            {"qop": "Measure", "args": [["q", 2]], "returns": [["m", 2]]},
            {"cop": "Result", "args": ["m"], "returns": ["result"]}
        ]
    }"#;

    // Use the improved converter
    let module = phir_json_to_module(json)?;

    // Create PhirEngine with the improved module
    let engine = PhirEngine::new(module)
        .map_err(|e| PecosError::Input(format!("Failed to create PhirEngine: {}", e)))?;

    let num_qubits = engine.num_qubits();
    let quantum_engine = Box::new(StateVecEngine::new(num_qubits));

    let mut hybrid_engine = HybridEngineBuilder::new()
        .with_classical_engine(Box::new(engine))
        .with_quantum_engine(quantum_engine)
        .build();

    // Debug: Print the module to see SSA IDs
    println!("Three-bit test module operations:");
    let module_for_debug = phir_json_to_module(json)?;
    for (i, op) in module_for_debug.body.blocks[0].operations.iter().enumerate() {
        println!("  {}: {:?}", i, op.operation);
        if !op.operands.is_empty() {
            println!("    Operands: {:?}", op.operands);
        }
        if !op.results.is_empty() {
            println!("    Results: {:?}", op.results);
        }
    }

    // Run a shot
    println!("About to run shot...");
    let shot = hybrid_engine.run_shot()?;
    println!("Shot completed!");

    println!("Shot data: {:?}", shot.data);

    if let Some(Data::U32(value)) = shot.data.get("result") {
        println!("Three-bit measurement result: {:03b}", value);
        assert!(*value <= 7, "Three-bit value should be 0-7");
    } else {
        panic!("Expected 'result' key in output, got keys: {:?}", shot.data.keys().collect::<Vec<_>>());
    }

    Ok(())
}