use super::*;

fn pattern(signed: bool, width: u16, words: &[u64]) -> ExprValue {
    let bits = BitUInt::from_raw_words(width, words.into());
    if signed {
        ExprValue::Signed(bits)
    } else {
        ExprValue::Unsigned(bits)
    }
}

// Input construction only. Expected words below are independent literals,
// never generated by this helper or by the evaluator's arithmetic helpers.
fn signed_input(width: u16, value: i64) -> ExprValue {
    pattern(
        true,
        width,
        &[
            value.cast_unsigned(),
            if value < 0 { 68_719_476_735 } else { 0 },
        ],
    )
}

fn assert_integer(value: ExprValue, signed: bool, width: u16, words: &[u64]) {
    assert_eq!(matches!(value, ExprValue::Signed(_)), signed, "{value:?}");
    let (ExprValue::Signed(bits) | ExprValue::Unsigned(bits)) = value else {
        panic!("expected integer, got {value:?}");
    };
    assert_eq!(bits.size(), width);
    assert_eq!(bits.to_words(), words);
}

#[test]
fn signed_reference_division_and_remainder() {
    // Reference rows computed independently with arbitrary-precision integers: low words encode -3, -1, 1, 3 and -8.
    for width in [64, 100] {
        for (op, a, b, low, high) in [
            ("/", -7, 2, 18_446_744_073_709_551_613, 68_719_476_735),
            ("%", -7, 2, 18_446_744_073_709_551_615, 68_719_476_735),
            ("/", 7, -2, 18_446_744_073_709_551_613, 68_719_476_735),
            ("%", 7, -2, 1, 0),
            ("/", -7, -2, 3, 0),
            ("%", -7, -2, 18_446_744_073_709_551_615, 68_719_476_735),
            ("/", -8, 1, 18_446_744_073_709_551_608, 68_719_476_735),
            ("/", 1, -1, 18_446_744_073_709_551_615, 68_719_476_735),
        ] {
            let expected = [low, high];
            assert_integer(
                eval_binary_op(op, signed_input(width, a), signed_input(width, b)).unwrap(),
                true,
                width,
                &expected[..if width == 64 { 1 } else { 2 }],
            );
        }
    }
}

#[test]
fn arithmetic_right_shift_reference_words() {
    for width in [64, 100] {
        for (a, count, low) in [
            (-8, 1, 18_446_744_073_709_551_612),
            (-1, 5, 18_446_744_073_709_551_615),
            (-1024, 10, 18_446_744_073_709_551_615),
            (-1024, 3, 18_446_744_073_709_551_488),
        ] {
            let expected = [low, 68_719_476_735];
            assert_integer(
                eval_binary_op(">>", signed_input(width, a), signed_input(width, count)).unwrap(),
                true,
                width,
                &expected[..if width == 64 { 1 } else { 2 }],
            );
        }
    }
    assert_integer(
        eval_binary_op(
            ">>",
            pattern(true, 100, &[0, 68_719_476_672]),
            ExprValue::signed(3),
        )
        .unwrap(),
        true,
        100,
        &[0, 68_719_476_728],
    );
}

#[test]
fn wide_divisor_with_zero_low_word() {
    let a = pattern(true, 100, &[0, 68_719_476_608]); // -(2^71)
    let b = pattern(true, 100, &[0, 68_719_476_672]); // -(2^70)
    assert_integer(
        eval_binary_op("/", a.clone(), b.clone()).unwrap(),
        true,
        100,
        &[2, 0],
    );
    assert_integer(eval_binary_op("%", a, b).unwrap(), true, 100, &[0, 0]);
}

#[test]
fn signed_comparison_full_width() {
    assert_integer(
        eval_binary_op(
            "<",
            pattern(true, 100, &[0, 68_719_476_672]),
            pattern(true, 100, &[0, 68_719_476_704]),
        )
        .unwrap(),
        false,
        64,
        &[1],
    );
    for width in [64, 100] {
        assert_integer(
            eval_binary_op("<", signed_input(width, -1), signed_input(width, 1)).unwrap(),
            false,
            64,
            &[1],
        );
        assert_integer(
            eval_binary_op(
                ">",
                pattern(false, width, &[u64::MAX, 68_719_476_735]),
                pattern(false, width, &[1, 0]),
            )
            .unwrap(),
            false,
            64,
            &[1],
        );
    }
}

#[test]
fn comparisons_always_return_unsigned_64() {
    for (op, expected) in [
        ("==", 0),
        ("!=", 1),
        ("<", 1),
        (">", 0),
        ("<=", 1),
        (">=", 0),
    ] {
        assert_integer(
            eval_binary_op(op, signed_input(100, -2), signed_input(100, -1)).unwrap(),
            false,
            64,
            &[expected],
        );
    }
}

#[test]
fn widening_preserves_signed_and_unsigned_patterns() {
    assert_integer(
        eval_binary_op("+", ExprValue::signed(-1), signed_input(100, 0)).unwrap(),
        true,
        100,
        &[18_446_744_073_709_551_615, 68_719_476_735],
    );
    assert_integer(
        eval_binary_op(
            "+",
            ExprValue::unsigned(9_223_372_036_854_775_808),
            signed_input(100, 0),
        )
        .unwrap(),
        false,
        100,
        &[9_223_372_036_854_775_808, 0],
    );
    // Unequal widths: sign-extended -1 is greater than -2, and equals wide -1.
    assert_integer(
        eval_binary_op(">", ExprValue::signed(-1), signed_input(100, -2)).unwrap(),
        false,
        64,
        &[1],
    );
    assert_integer(
        eval_binary_op("==", ExprValue::signed(-1), signed_input(100, -1)).unwrap(),
        false,
        64,
        &[1],
    );
    assert_integer(
        eval_binary_op("<", pattern(true, 8, &[128]), ExprValue::signed(-1)).unwrap(),
        false,
        64,
        &[1],
    );
}

#[test]
fn sign_extending_resize_boundaries() {
    for (source, target, input, expected) in [
        (8, 8, vec![128], vec![128]),
        (8, 4, vec![128], vec![0]),
        (8, 65, vec![128], vec![18_446_744_073_709_551_488, 1]),
        (8, 100, vec![127], vec![127, 0]),
        (65, 100, vec![0, 1], vec![0, 68_719_476_735]),
        (100, 64, vec![7, 68_719_476_735], vec![7]),
        (
            1,
            100,
            vec![1],
            vec![18_446_744_073_709_551_615, 68_719_476_735],
        ),
    ] {
        let result =
            BitUInt::from_raw_words(source, input.into_boxed_slice()).resize_sign_extend(target);
        assert_eq!(result.size(), target);
        assert_eq!(result.to_words(), expected);
    }
}

#[test]
fn signed_minimum_divided_by_negative_one_wraps() {
    // -(2^(w-1)) / -1 has magnitude 2^(w-1), which wraps back to
    // signed minimum at width w. Division is exact, so remainder is zero.
    for (width, minimum, zero) in [
        (64, vec![9_223_372_036_854_775_808], vec![0]),
        (100, vec![0, 34_359_738_368], vec![0, 0]),
    ] {
        let input = pattern(true, width, &minimum);
        assert_integer(
            eval_binary_op("/", input.clone(), signed_input(width, -1)).unwrap(),
            true,
            width,
            &minimum,
        );
        assert_integer(
            eval_binary_op("%", input, signed_input(width, -1)).unwrap(),
            true,
            width,
            &zero,
        );
    }
}

#[test]
fn unary_minus_is_signed_at_evaluation_width() {
    // Decimals computed independently with arbitrary-precision integers: 1267650600228229401496703205373 (-3 pattern),
    // and 633825300114114700748351602688 (2^99, unchanged by negation).
    assert_integer(
        eval_unary_op("-", pattern(false, 100, &[3, 0])).unwrap(),
        true,
        100,
        &[18_446_744_073_709_551_613, 68_719_476_735],
    );
    assert_integer(
        eval_unary_op("-", pattern(false, 100, &[0, 34_359_738_368])).unwrap(),
        true,
        100,
        &[0, 34_359_738_368],
    );
    assert_integer(
        eval_unary_op("-", pattern(false, 8, &[3])).unwrap(),
        true,
        64,
        &[18_446_744_073_709_551_613],
    );
    assert_integer(
        eval_unary_op("-", pattern(true, 8, &[253])).unwrap(),
        true,
        64,
        &[3],
    );
    assert_integer(
        eval_unary_op("-", ExprValue::Boolean(true)).unwrap(),
        true,
        64,
        &[18_446_744_073_709_551_615],
    );
    assert_integer(
        eval_unary_op("-", ExprValue::Boolean(false)).unwrap(),
        true,
        64,
        &[0],
    );
}

#[test]
fn narrow_binary_uses_width_floor() {
    assert_integer(
        eval_binary_op("+", pattern(false, 8, &[255]), pattern(false, 8, &[1])).unwrap(),
        false,
        64,
        &[256],
    );
    assert_integer(
        eval_binary_op("+", pattern(true, 8, &[255]), pattern(true, 8, &[255])).unwrap(),
        true,
        64,
        &[18_446_744_073_709_551_614],
    );
    assert_integer(
        eval_binary_op("+", ExprValue::Boolean(true), ExprValue::Boolean(true)).unwrap(),
        false,
        64,
        &[2],
    );
}

#[test]
fn unary_complement_and_logical_not() {
    assert_integer(
        eval_unary_op("~", pattern(false, 8, &[255])).unwrap(),
        false,
        64,
        &[18_446_744_073_709_551_360],
    );
    assert_integer(
        eval_unary_op("~", pattern(true, 8, &[255])).unwrap(),
        true,
        64,
        &[0],
    );
    assert_integer(
        eval_unary_op("~", pattern(true, 100, &[0, 0])).unwrap(),
        true,
        100,
        &[18_446_744_073_709_551_615, 68_719_476_735],
    );
    assert_eq!(
        eval_unary_op("~", ExprValue::Boolean(true)).unwrap(),
        ExprValue::Boolean(false)
    );
    assert_eq!(
        eval_unary_op("!", pattern(false, 100, &[0, 1])).unwrap(),
        ExprValue::Boolean(false)
    );
    assert_eq!(
        eval_unary_op("!", ExprValue::Boolean(false)).unwrap(),
        ExprValue::Boolean(true)
    );
}

#[test]
fn mixed_binary_tags_require_both_signed() {
    for width in [64, 100] {
        for (op, expected) in [
            ("+", 9),
            ("-", 3),
            ("*", 18),
            ("/", 2),
            ("%", 0),
            ("&", 2),
            ("|", 7),
            ("^", 5),
            ("<<", 48),
        ] {
            for (left_signed, right_signed) in
                [(true, false), (false, true), (false, false), (true, true)]
            {
                let words = [expected, 0];
                assert_integer(
                    eval_binary_op(
                        op,
                        pattern(left_signed, width, &[6, 0]),
                        pattern(right_signed, width, &[3, 0]),
                    )
                    .unwrap(),
                    left_signed && right_signed,
                    width,
                    &words[..if width == 64 { 1 } else { 2 }],
                );
            }
        }
    }
}

#[test]
fn boolean_integer_promotion_in_every_family() {
    // true is unsigned 1, even beside a signed integer. These expectations
    // cover both orders; right shift alone follows the left operand's tag.
    for (op, left, right) in [
        ("+", 4, 4),
        ("-", 2, 18_446_744_073_709_551_614),
        ("*", 3, 3),
        ("/", 3, 0),
        ("%", 0, 1),
        ("&", 1, 1),
        ("|", 3, 3),
        ("^", 2, 2),
        ("<<", 6, 8),
    ] {
        assert_integer(
            eval_binary_op(op, ExprValue::signed(3), ExprValue::Boolean(true)).unwrap(),
            false,
            64,
            &[left],
        );
        assert_integer(
            eval_binary_op(op, ExprValue::Boolean(true), ExprValue::signed(3)).unwrap(),
            false,
            64,
            &[right],
        );
    }
    for (op, left, right) in [
        ("==", 0, 0),
        ("!=", 1, 1),
        ("<", 0, 1),
        (">", 1, 0),
        ("<=", 0, 1),
        (">=", 1, 0),
    ] {
        assert_integer(
            eval_binary_op(op, ExprValue::signed(-1), ExprValue::Boolean(true)).unwrap(),
            false,
            64,
            &[left],
        );
        assert_integer(
            eval_binary_op(op, ExprValue::Boolean(true), ExprValue::signed(-1)).unwrap(),
            false,
            64,
            &[right],
        );
    }
    assert_integer(
        eval_binary_op(">>", ExprValue::signed(3), ExprValue::Boolean(true)).unwrap(),
        true,
        64,
        &[1],
    );
    assert_integer(
        eval_binary_op(">>", ExprValue::Boolean(true), ExprValue::signed(3)).unwrap(),
        false,
        64,
        &[0],
    );
    assert_integer(
        eval_binary_op("+", ExprValue::Boolean(true), signed_input(100, 3)).unwrap(),
        false,
        100,
        &[4, 0],
    );
    for op in ["&&", "||"] {
        assert_eq!(
            eval_binary_op(op, ExprValue::Boolean(true), ExprValue::signed(3)).unwrap(),
            ExprValue::Boolean(true)
        );
        assert_eq!(
            eval_binary_op(op, ExprValue::signed(3), ExprValue::Boolean(false)).unwrap(),
            ExprValue::Boolean(op == "||")
        );
    }
}

#[test]
fn signed_right_shift_keeps_left_tag() {
    assert_integer(
        eval_binary_op(">>", ExprValue::signed(-8), ExprValue::unsigned(1)).unwrap(),
        true,
        64,
        &[18_446_744_073_709_551_612],
    );
    assert_integer(
        eval_binary_op(">>", signed_input(100, -8), ExprValue::unsigned(1)).unwrap(),
        true,
        100,
        &[18_446_744_073_709_551_612, 68_719_476_735],
    );
    assert_integer(
        eval_binary_op(">>", ExprValue::unsigned(8), ExprValue::signed(1)).unwrap(),
        false,
        64,
        &[4],
    );
}

#[test]
fn legacy_shift_counts_64() {
    // count, logical 1 << count, logical high-bit >> count,
    // arithmetic -8 >> (count % 64). 65536 truncates to zero.
    for (count, left, right, arithmetic) in [
        (0, 1, 9_223_372_036_854_775_808, 18_446_744_073_709_551_608),
        (1, 2, 4_611_686_018_427_387_904, 18_446_744_073_709_551_612),
        (63, 9_223_372_036_854_775_808, 1, 18_446_744_073_709_551_615),
        (64, 0, 0, 18_446_744_073_709_551_608),
        (65, 0, 0, 18_446_744_073_709_551_612),
        (65535, 0, 0, 18_446_744_073_709_551_615),
        (
            65536,
            1,
            9_223_372_036_854_775_808,
            18_446_744_073_709_551_608,
        ),
        (
            65537,
            2,
            4_611_686_018_427_387_904,
            18_446_744_073_709_551_612,
        ),
    ] {
        for rhs in [
            ExprValue::signed(count),
            ExprValue::unsigned(u64::try_from(count).unwrap()),
        ] {
            assert_integer(
                eval_binary_op("<<", ExprValue::unsigned(1), rhs.clone()).unwrap(),
                false,
                64,
                &[left],
            );
            assert_integer(
                eval_binary_op(
                    ">>",
                    ExprValue::unsigned(9_223_372_036_854_775_808),
                    rhs.clone(),
                )
                .unwrap(),
                false,
                64,
                &[right],
            );
            assert_integer(
                eval_binary_op(">>", ExprValue::signed(-8), rhs.clone()).unwrap(),
                true,
                64,
                &[arithmetic],
            );
            let signed_rhs = matches!(rhs, ExprValue::Signed(_));
            assert_integer(
                eval_binary_op("<<", ExprValue::signed(1), rhs).unwrap(),
                signed_rhs,
                64,
                &[left],
            );
        }
    }
}

#[test]
fn unsigned_high_bit_shift_count_is_negative() {
    for op in ["<<", ">>"] {
        for lhs in [ExprValue::signed(-8), ExprValue::unsigned(8)] {
            let error = eval_binary_op(op, lhs, ExprValue::unsigned(9_223_372_036_854_775_808))
                .unwrap_err();
            assert!(
                matches!(error, PecosError::Input(message) if message == "Negative shift amount: -9223372036854775808")
            );
        }
    }
}

#[test]
fn wide_shift_counts_and_modulo() {
    for (count, expected) in [
        (100, 18_446_744_073_709_551_608),
        (101, 18_446_744_073_709_551_612),
        (65536, 18_446_744_073_709_551_608),
        (65537, 18_446_744_073_709_551_612),
    ] {
        assert_integer(
            eval_binary_op(">>", signed_input(100, -8), ExprValue::signed(count)).unwrap(),
            true,
            100,
            &[expected, 68_719_476_735],
        );
    }
    // The accessor returns zero, not the low word, when any high word is set.
    assert_integer(
        eval_binary_op("<<", ExprValue::unsigned(3), pattern(false, 100, &[1, 1])).unwrap(),
        false,
        100,
        &[3, 0],
    );
}

#[test]
fn errors_and_lossy_accessors_are_preserved() {
    let wide = signed_input(100, -1);
    assert_eq!(wide.as_i64(), 0);
    assert_eq!(wide.as_u64(), 0);
    assert!(wide.as_bool());
    assert_eq!(wide.to_string(), "0");
    for op in ["/", "%"] {
        for signed in [false, true] {
            assert!(matches!(
                eval_binary_op(
                    op,
                    pattern(signed, 100, &[1, 1]),
                    pattern(signed, 100, &[0, 0])
                ),
                Err(PecosError::RuntimeDivisionByZero)
            ));
        }
    }
    assert!(
        matches!(eval_binary_op("?", ExprValue::signed(1), ExprValue::signed(1)), Err(PecosError::Input(message)) if message == "Unsupported binary operation: ?")
    );
    assert!(
        matches!(eval_unary_op("?", ExprValue::signed(1)), Err(PecosError::Input(message)) if message == "Unsupported unary operation: ?")
    );
}

#[test]
fn narrow_signed_shift_count_is_read_before_widening() {
    // An eight-bit signed 0xFF is negative one at its own width, but the count
    // is read before the operands widen, so it shifts by 255 and does not
    // error. Reading it after widening would sign-extend it to u64::MAX, whose
    // lossy reading is negative one, and the call would fail instead.
    assert_integer(
        eval_binary_op(">>", ExprValue::signed(-8), pattern(true, 8, &[0xFF])).unwrap(),
        true,
        64,
        &[u64::MAX],
    );
    // A 64-bit signed negative count still errors, which is what the read
    // order preserves.
    assert!(
        eval_binary_op(">>", ExprValue::signed(-8), ExprValue::signed(-1))
            .unwrap_err()
            .to_string()
            .contains("Negative shift amount")
    );
}

#[test]
fn shift_count_truncates_to_sixteen_bits_not_eight() {
    // 300 survives a 16-bit truncation and so reaches the width, giving zero.
    // An 8-bit truncation would leave 44 and shift by that instead.
    assert_integer(
        eval_binary_op("<<", ExprValue::unsigned(1), ExprValue::unsigned(300)).unwrap(),
        false,
        64,
        &[0],
    );
    assert_integer(
        eval_binary_op(">>", ExprValue::unsigned(1 << 60), ExprValue::unsigned(300)).unwrap(),
        false,
        64,
        &[0],
    );
}
