use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    // Tell Cargo to rerun this build script if the includes directory changes
    println!("cargo:rerun-if-changed=includes/");

    // Get the includes directory
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let includes_dir = Path::new(&manifest_dir).join("includes");

    // Generate the includes module content
    let mut includes_content = String::new();
    includes_content
        .push_str("// This file is auto-generated by build.rs. Do not edit manually.\n\n");

    // Find all .inc files
    let mut inc_files = Vec::new();
    if let Ok(entries) = fs::read_dir(&includes_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("inc")
                && let Some(filename) = path.file_name().and_then(|s| s.to_str())
            {
                inc_files.push(filename.to_string());
            }
        }
    }

    // Sort for consistent output
    inc_files.sort();

    // Generate the function that returns all includes
    includes_content.push_str("/// Get all standard virtual includes\n");
    includes_content.push_str("#[must_use]\n");
    includes_content
        .push_str("pub fn get_standard_includes() -> Vec<(&'static str, &'static str)> {\n");
    includes_content.push_str("    vec![\n");

    for filename in &inc_files {
        // Use concat! with env! to get the correct path
        writeln!(
            includes_content,
            "        (\"{filename}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/includes/{filename}\"))),",
        ).unwrap();
    }

    includes_content.push_str("    ]\n");
    includes_content.push_str("}\n");

    // Write to the generated file
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("includes_generated.rs");
    fs::write(dest_path, includes_content).unwrap();
}
