# Copyright 2026 The PECOS Developers
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.

"""Typed surface for the dynamically registered ``pecos_rslib.qec`` module."""

from __future__ import annotations

from typing import Any

from pecos_rslib import DistanceResult, ParityCheckMatrix, StabilizerCodeSpec, TickCircuit

class BivariateBicycleCode:
    """A validated bivariate-bicycle CSS code."""

    def __init__(
        self,
        l: int,
        m: int,
        a_terms: list[tuple[int, int]],
        b_terms: list[tuple[int, int]],
    ) -> None: ...
    @property
    def l_order(self) -> int: ...
    @property
    def m_order(self) -> int: ...
    @property
    def hx(self) -> ParityCheckMatrix: ...
    @property
    def hz(self) -> ParityCheckMatrix: ...
    @property
    def logical_x(self) -> ParityCheckMatrix: ...
    @property
    def logical_z(self) -> ParityCheckMatrix: ...
    def num_qubits(self) -> int: ...
    def num_logical_qubits(self) -> int: ...

def bb_memory_circuit(
    l: int,
    m: int,
    a_terms: list[tuple[int, int]],
    b_terms: list[tuple[int, int]],
    rounds: int,
    basis: str,
) -> TickCircuit: ...
def coloration_memory_circuit(
    hx: ParityCheckMatrix,
    hz: ParityCheckMatrix,
    rounds: int,
    basis: str,
) -> TickCircuit: ...

class FaultDistanceResult:
    """A unit-weight mechanism distance and one witnessing index set."""

    @property
    def distance(self) -> int: ...
    @property
    def mechanism_indices(self) -> list[int]: ...
    def __repr__(self) -> str: ...

class DetectorErrorModel:
    """Rust-backed detector error model."""

    def graphlike_fault_distance(self) -> FaultDistanceResult | None: ...
    def connected_cluster_fault_distance(self, max_weight: int) -> FaultDistanceResult | None: ...
    def per_observable_fault_distances(self, max_weight: int) -> list[FaultDistanceResult | None]: ...
    def exhaustive_fault_distance(self, max_weight: int) -> FaultDistanceResult | None: ...
    def __getattr__(self, name: str) -> Any: ...

class CircuitFaultLocation:
    """A Pauli-fault location in a tick circuit."""

    @property
    def tick(self) -> int: ...
    @property
    def gate_type(self) -> str: ...
    @property
    def qubits(self) -> list[int]: ...
    @property
    def gate_index(self) -> int: ...
    @property
    def before(self) -> bool: ...
    def __repr__(self) -> str: ...

class HookError:
    """A single-location fault that amplifies across the data block."""

    @property
    def location(self) -> CircuitFaultLocation: ...
    @property
    def fault_paulis(self) -> list[int]: ...
    @property
    def data_support(self) -> list[int]: ...
    @property
    def data_weight(self) -> int: ...
    @property
    def detected(self) -> bool: ...
    @property
    def causes_logical_error(self) -> bool: ...
    def __repr__(self) -> str: ...

class HookErrorReport:
    """Summary of hook-error diagnosis over a selected Pauli fault set."""

    @property
    def hook_errors(self) -> list[HookError]: ...
    @property
    def total_faults_examined(self) -> int: ...
    @property
    def max_data_weight(self) -> int: ...
    def __repr__(self) -> str: ...

class FlagViolation:
    """A counterexample to the propagated-fault condition for a flag circuit."""

    @property
    def faults(self) -> list[tuple[CircuitFaultLocation, list[int]]]: ...
    @property
    def num_faults(self) -> int: ...
    @property
    def error_weight(self) -> int: ...
    def __repr__(self) -> str: ...

class FlagFaultToleranceReport:
    """Result of checking the propagated-fault condition through fault weight ``t``."""

    @property
    def fault_condition_satisfied(self) -> bool: ...
    @property
    def t(self) -> int: ...
    @property
    def violations(self) -> list[FlagViolation]: ...
    @property
    def total_configurations_tested(self) -> int: ...
    def __repr__(self) -> str: ...

class CircuitDistanceResult:
    """A circuit fault distance and its first iterator-ordered witness."""

    @property
    def distance(self) -> int: ...
    @property
    def witness(self) -> list[tuple[CircuitFaultLocation, list[int]]]: ...
    @property
    def logical_index(self) -> int: ...
    def __repr__(self) -> str: ...

class CircuitFaultAnalyzer:
    """Fault-tolerance diagnostics and distance searches for a tick circuit."""

    def __init__(self, circuit: TickCircuit) -> None: ...
    def hook_errors(
        self,
        data_qubits: list[int],
        z_ancillas: list[int],
        x_ancillas: list[int],
        logicals: list[tuple[list[int], list[int]]],
        min_data_weight: int,
        *,
        x_only: bool = False,
        y_only: bool = False,
        z_only: bool = False,
    ) -> HookErrorReport: ...
    def flag_fault_condition(
        self,
        data_qubits: list[int],
        flag_qubits: list[int],
        measured_stabilizer: tuple[list[int], list[int]],
        t: int,
        *,
        x_only: bool = False,
        y_only: bool = False,
        z_only: bool = False,
    ) -> FlagFaultToleranceReport: ...
    def fault_distance(
        self,
        z_ancillas: list[int],
        x_ancillas: list[int],
        logicals: list[tuple[list[int], list[int]]],
        max_weight: int,
        *,
        x_only: bool = False,
        y_only: bool = False,
        z_only: bool = False,
    ) -> CircuitDistanceResult | None: ...
    def per_logical_fault_distances(
        self,
        z_ancillas: list[int],
        x_ancillas: list[int],
        logicals: list[tuple[list[int], list[int]]],
        max_weight: int,
        *,
        x_only: bool = False,
        y_only: bool = False,
        z_only: bool = False,
    ) -> list[CircuitDistanceResult | None]: ...
    def __repr__(self) -> str: ...

class CertifiedDistance:
    """A natively checked SAT witness and solver-trusted UNSAT prefix."""

    @property
    def distance(self) -> int: ...
    @property
    def witness(self) -> list[bool]: ...
    @property
    def sat_certified(self) -> bool: ...
    @property
    def unsat_trusted_below(self) -> int: ...
    def __repr__(self) -> str: ...

class DistanceProblem:
    """A binary undetectable-error problem with nonzero logical effect."""

    @classmethod
    def from_css_checks(cls, hx: ParityCheckMatrix, lx: ParityCheckMatrix) -> DistanceProblem: ...
    @classmethod
    def from_css_code_x_distance(cls, spec: StabilizerCodeSpec) -> DistanceProblem: ...
    @classmethod
    def from_css_code_z_distance(cls, spec: StabilizerCodeSpec) -> DistanceProblem: ...
    @classmethod
    def from_dem(cls, dem: DetectorErrorModel) -> DistanceProblem: ...
    @property
    def num_vars(self) -> int: ...
    def to_dimacs(self, max_weight: int) -> str: ...
    def to_wcnf(self) -> str: ...
    def verify_witness(self, witness: list[bool]) -> int: ...
    def certified_distance(self, max_weight: int) -> CertifiedDistance | None: ...
    def __repr__(self) -> str: ...

def certified_distance(problem: DistanceProblem, max_weight: int) -> CertifiedDistance | None: ...
def connected_cluster_code_distance(
    h: ParityCheckMatrix,
    l: ParityCheckMatrix,
    max_weight: int,
) -> FaultDistanceResult | None: ...
def x_distance(spec: StabilizerCodeSpec, max_weight: int) -> FaultDistanceResult | None: ...
def z_distance(spec: StabilizerCodeSpec, max_weight: int) -> FaultDistanceResult | None: ...
def stabilizer_code_distance(spec: StabilizerCodeSpec, max_weight: int) -> DistanceResult | None: ...

# The native QEC module predates this focused stub. Preserve the untyped behavior of its other
# classes and functions until that complete API is migrated rather than falsely narrowing them.
def __getattr__(name: str) -> Any: ...
def certified_coset_weight(
    group: ParityCheckMatrix, representative: list[int], max_weight: int
) -> CertifiedDistance | None: ...
def certified_stabilizer_coset_weight(
    code: StabilizerCodeSpec, operator: Any, max_weight: int
) -> CertifiedDistance | None: ...
def logical_coset_weight_profile(code: StabilizerCodeSpec, max_weight: int) -> list[CertifiedDistance | None]: ...
def certified_classical_distance(h: ParityCheckMatrix, max_weight: int) -> CertifiedDistance | None: ...

class HypergraphProductCode:
    """A hypergraph-product CSS code built from two classical parity-check matrices."""

    def __init__(self, h1: ParityCheckMatrix, h2: ParityCheckMatrix) -> None: ...
    @property
    def hx(self) -> ParityCheckMatrix: ...
    @property
    def hz(self) -> ParityCheckMatrix: ...
    @property
    def logical_x(self) -> ParityCheckMatrix: ...
    @property
    def logical_z(self) -> ParityCheckMatrix: ...
    def num_qubits(self) -> int: ...
    def num_logical_qubits(self) -> int: ...
