//! Circuit Compiler - Generates specialized WGSL shaders for specific gate sequences
//!
//! For repeated circuits (like syndrome extraction rounds), compiling to a specialized
//! shader eliminates:
//! - Gate queue buffer writes
//! - Loop iteration overhead
//! - Switch statement dispatch
//!
//! This can provide significant speedups for circuits that are executed many times.

use std::collections::HashMap;
use std::fmt::Write;
use std::hash::{Hash, Hasher};

/// Gate types matching the shader constants
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GateType {
    H,
    S,
    Sdg,
    X,
    Y,
    Z,
    Cx,
    Cz,
    Swap,
}

/// A gate in the circuit
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Gate {
    pub gate_type: GateType,
    pub target: u32,
    pub control: Option<u32>, // None for single-qubit gates
}

impl Gate {
    #[must_use]
    pub fn h(target: u32) -> Self {
        Self {
            gate_type: GateType::H,
            target,
            control: None,
        }
    }

    #[must_use]
    pub fn s(target: u32) -> Self {
        Self {
            gate_type: GateType::S,
            target,
            control: None,
        }
    }

    #[must_use]
    pub fn sdg(target: u32) -> Self {
        Self {
            gate_type: GateType::Sdg,
            target,
            control: None,
        }
    }

    #[must_use]
    pub fn x(target: u32) -> Self {
        Self {
            gate_type: GateType::X,
            target,
            control: None,
        }
    }

    #[must_use]
    pub fn y(target: u32) -> Self {
        Self {
            gate_type: GateType::Y,
            target,
            control: None,
        }
    }

    #[must_use]
    pub fn z(target: u32) -> Self {
        Self {
            gate_type: GateType::Z,
            target,
            control: None,
        }
    }

    #[must_use]
    pub fn cx(control: u32, target: u32) -> Self {
        Self {
            gate_type: GateType::Cx,
            target,
            control: Some(control),
        }
    }

    #[must_use]
    pub fn cz(a: u32, b: u32) -> Self {
        Self {
            gate_type: GateType::Cz,
            target: b,
            control: Some(a),
        }
    }

    #[must_use]
    pub fn swap(a: u32, b: u32) -> Self {
        Self {
            gate_type: GateType::Swap,
            target: b,
            control: Some(a),
        }
    }
}

/// A compiled circuit ready for GPU execution
#[derive(Debug, Clone)]
pub struct CompiledCircuit {
    pub wgsl_source: String,
    pub entry_point: String,
    pub num_gates: usize,
    pub hash: u64,
}

/// Circuit compiler that generates specialized WGSL shaders
pub struct CircuitCompiler {
    cache: HashMap<u64, CompiledCircuit>,
}

impl CircuitCompiler {
    #[must_use]
    pub fn new() -> Self {
        Self {
            cache: HashMap::new(),
        }
    }

    /// Compute a hash for a gate sequence
    fn compute_hash(gates: &[Gate]) -> u64 {
        use std::collections::hash_map::DefaultHasher;
        let mut hasher = DefaultHasher::new();
        gates.hash(&mut hasher);
        hasher.finish()
    }

    /// Compile a gate sequence to a specialized WGSL shader
    ///
    /// # Panics
    /// Panics if the cache entry is unexpectedly missing after insertion.
    pub fn compile(&mut self, gates: &[Gate]) -> &CompiledCircuit {
        let hash = Self::compute_hash(gates);

        self.cache
            .entry(hash)
            .or_insert_with(|| Self::generate_shader(gates, hash));

        self.cache.get(&hash).unwrap()
    }

    /// Check if a circuit is already compiled
    #[must_use]
    pub fn is_cached(&self, gates: &[Gate]) -> bool {
        let hash = Self::compute_hash(gates);
        self.cache.contains_key(&hash)
    }

    /// Generate WGSL shader for a gate sequence
    fn generate_shader(gates: &[Gate], hash: u64) -> CompiledCircuit {
        let entry_point = format!("compiled_circuit_{hash:016x}");

        let mut wgsl = String::new();

        // Header
        write!(
            wgsl,
            r"// Compiled circuit shader (hash: {:016x})
// {} gates, generated by CircuitCompiler

@group(0) @binding(0) var<storage, read_write> stab_x: array<u32>;
@group(0) @binding(1) var<storage, read_write> stab_z: array<u32>;
@group(0) @binding(2) var<storage, read_write> destab_x: array<u32>;
@group(0) @binding(3) var<storage, read_write> destab_z: array<u32>;
@group(0) @binding(4) var<storage, read_write> sign_minus: array<u32>;
@group(0) @binding(7) var<storage, read_write> sign_i: array<u32>;

struct Params {{
    num_qubits: u32,
    gen_words: u32,
    num_gens: u32,
    _pad1: u32,
    _pad2: u32,
    _pad3: u32,
    _pad4: u32,
    _pad5: u32,
}}

@group(0) @binding(5) var<uniform> params: Params;

@compute @workgroup_size(256)
fn {}(
    @builtin(global_invocation_id) global_id: vec3<u32>
) {{
    let word_idx = global_id.x;
    if (word_idx >= params.gen_words) {{
        return;
    }}

    var local_sign_minus = sign_minus[word_idx];
    var local_sign_i = sign_i[word_idx];
    let gw = params.gen_words;

",
            hash,
            gates.len(),
            entry_point
        )
        .unwrap();

        // Generate code for each gate
        for (i, gate) in gates.iter().enumerate() {
            writeln!(wgsl, "    // Gate {}: {:?}", i, gate.gate_type).unwrap();
            wgsl.push_str(&Self::generate_gate_code(gate));
            wgsl.push('\n');
        }

        // Footer
        wgsl.push_str(
            r"
    sign_minus[word_idx] = local_sign_minus;
    sign_i[word_idx] = local_sign_i;
}
",
        );

        CompiledCircuit {
            wgsl_source: wgsl,
            entry_point,
            num_gates: gates.len(),
            hash,
        }
    }

    /// Generate WGSL code for a single gate
    fn generate_gate_code(gate: &Gate) -> String {
        match gate.gate_type {
            GateType::H => format!(
                r"    {{
        let off = {}u * gw + word_idx;
        let ox = stab_x[off];
        let oz = stab_z[off];
        stab_x[off] = oz;
        stab_z[off] = ox;
        let dx = destab_x[off];
        let dz = destab_z[off];
        destab_x[off] = dz;
        destab_z[off] = dx;
        local_sign_minus ^= (ox & oz);
    }}
",
                gate.target
            ),

            GateType::S => format!(
                r"    {{
        let off = {}u * gw + word_idx;
        let ox = stab_x[off];
        let oz = stab_z[off];
        stab_z[off] = oz ^ ox;
        let dx = destab_x[off];
        let dz = destab_z[off];
        destab_z[off] = dz ^ dx;
        // S: when X is set with existing i phase, toggle minus (i*i = -1)
        local_sign_minus ^= (ox & local_sign_i);
        local_sign_i ^= ox;
    }}
",
                gate.target
            ),

            GateType::Sdg => format!(
                r"    {{
        let off = {}u * gw + word_idx;
        let ox = stab_x[off];
        let oz = stab_z[off];
        stab_z[off] = oz ^ ox;
        let dx = destab_x[off];
        let dz = destab_z[off];
        destab_z[off] = dz ^ dx;
        // Sdg multiplies phase by -i when X=1: flip sign_minus when sign_i was 0
        local_sign_minus ^= (ox & ~local_sign_i);
        local_sign_i ^= ox;
    }}
",
                gate.target
            ),

            GateType::X => format!(
                r"    {{
        let off = {}u * gw + word_idx;
        local_sign_minus ^= stab_z[off];
    }}
",
                gate.target
            ),

            GateType::Y => format!(
                r"    {{
        let off = {}u * gw + word_idx;
        local_sign_minus ^= (stab_x[off] ^ stab_z[off]);
    }}
",
                gate.target
            ),

            GateType::Z => format!(
                r"    {{
        let off = {}u * gw + word_idx;
        local_sign_minus ^= stab_x[off];
    }}
",
                gate.target
            ),

            GateType::Cx => {
                let ctrl = gate.control.unwrap();
                format!(
                    r"    {{
        let c_off = {}u * gw + word_idx;
        let t_off = {}u * gw + word_idx;
        // CX: X_tgt ^= X_ctrl, Z_ctrl ^= Z_tgt
        stab_x[t_off] = stab_x[t_off] ^ stab_x[c_off];
        stab_z[c_off] = stab_z[c_off] ^ stab_z[t_off];
        destab_x[t_off] = destab_x[t_off] ^ destab_x[c_off];
        destab_z[c_off] = destab_z[c_off] ^ destab_z[t_off];
        // CX does NOT require sign updates
    }}
",
                    ctrl, gate.target
                )
            }

            GateType::Cz => {
                let a = gate.control.unwrap();
                let b = gate.target;
                format!(
                    r"    {{
        let a_off = {a}u * gw + word_idx;
        let b_off = {b}u * gw + word_idx;
        let ax = stab_x[a_off];
        let bx = stab_x[b_off];
        stab_z[a_off] = stab_z[a_off] ^ bx;
        stab_z[b_off] = stab_z[b_off] ^ ax;
        let adx = destab_x[a_off];
        let bdx = destab_x[b_off];
        destab_z[a_off] = destab_z[a_off] ^ bdx;
        destab_z[b_off] = destab_z[b_off] ^ adx;
        // CZ: flip sign when both qubits have X
        local_sign_minus ^= (ax & bx);
    }}
"
                )
            }

            GateType::Swap => {
                let a = gate.control.unwrap();
                let b = gate.target;
                format!(
                    r"    {{
        let a_off = {a}u * gw + word_idx;
        let b_off = {b}u * gw + word_idx;
        let tmp_x = stab_x[a_off];
        stab_x[a_off] = stab_x[b_off];
        stab_x[b_off] = tmp_x;
        let tmp_z = stab_z[a_off];
        stab_z[a_off] = stab_z[b_off];
        stab_z[b_off] = tmp_z;
        let tmp_dx = destab_x[a_off];
        destab_x[a_off] = destab_x[b_off];
        destab_x[b_off] = tmp_dx;
        let tmp_dz = destab_z[a_off];
        destab_z[a_off] = destab_z[b_off];
        destab_z[b_off] = tmp_dz;
    }}
"
                )
            }
        }
    }
}

impl Default for CircuitCompiler {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compile_simple_circuit() {
        let mut compiler = CircuitCompiler::new();

        let gates = vec![Gate::h(0), Gate::cx(0, 1), Gate::h(1)];

        let compiled = compiler.compile(&gates);

        assert_eq!(compiled.num_gates, 3);
        assert!(compiled.wgsl_source.contains("stab_x"));
        assert!(compiled.wgsl_source.contains("stab_z"));
        println!("Generated shader:\n{}", compiled.wgsl_source);
    }

    #[test]
    fn test_cache_hit() {
        let mut compiler = CircuitCompiler::new();

        let gates = vec![Gate::h(0), Gate::h(1)];

        assert!(!compiler.is_cached(&gates));
        compiler.compile(&gates);
        assert!(compiler.is_cached(&gates));
    }

    #[test]
    #[allow(clippy::cast_sign_loss)] // all values are small non-negative surface code indices
    fn test_surface_code_round() {
        let mut compiler = CircuitCompiler::new();

        // Simplified surface code round (d=3)
        let d = 3;
        let num_data = d * d;
        let num_ancilla = num_data - 1;

        let mut gates = Vec::new();

        // X-type stabilizers
        for a in 0..num_ancilla / 2 {
            let ancilla = num_data + a;
            let base = a % num_data;

            gates.push(Gate::cx(ancilla as u32, base as u32));
            if base + 1 < num_data {
                gates.push(Gate::cx(ancilla as u32, (base + 1) as u32));
            }
            if base + d < num_data {
                gates.push(Gate::cx(ancilla as u32, (base + d) as u32));
            }
        }

        // Z-type stabilizers
        for a in num_ancilla / 2..num_ancilla {
            let ancilla = num_data + a;
            let base = a % num_data;

            gates.push(Gate::cx(base as u32, ancilla as u32));
            if base + 1 < num_data {
                gates.push(Gate::cx((base + 1) as u32, ancilla as u32));
            }
            if base + d < num_data {
                gates.push(Gate::cx((base + d) as u32, ancilla as u32));
            }
        }

        let compiled = compiler.compile(&gates);

        println!("Surface code d={} round: {} gates", d, compiled.num_gates);
        println!("Shader length: {} bytes", compiled.wgsl_source.len());

        // Verify the shader is valid WGSL (basic check)
        assert!(compiled.wgsl_source.contains("@compute"));
        assert!(compiled.wgsl_source.contains("@workgroup_size(256)"));
    }
}
