[package]
name = "pecos-hugr"
version.workspace = true
edition.workspace = true
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Static HUGR loading and result-tag analysis for PECOS"

[dependencies]
anyhow.workspace = true
tket.workspace = true
tket-qsystem.workspace = true

[lints]
workspace = true
