[package]
name = "pecos-pyo3"
version = "0.5.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pecos-sim = { workspace=true }

pyo3 = { workspace=true, features = ["extension-module"] }
