[package]
name = "pecos-pyo3"
version = "0.5.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pecos-sims = { path = "../crates/pecos-sims" }
pyo3 = { version = "0.20", features = ["extension-module"] }
