#!/usr/bin/env python3
# Copyright 2026 The PECOS Developers
# Licensed under the Apache License, Version 2.0
"""Move every Python distribution in the repository onto a new version.

The Python version train is a literal repeated across the root meta-package, every
distribution's `[project].version`, and the exact `==` pins distributions use for each
other. This rewrites all of them together so a release bump cannot half-land.

Distributions are discovered the same way `scripts/check_python_workspace.py` discovers
them, so a package added later is picked up without editing this script. Lockfiles are
regenerated by the `just bump-python-version` recipe that calls this.
"""

from __future__ import annotations

import argparse
import sys
from typing import TYPE_CHECKING

from check_python_workspace import (
    REPO_ROOT,
    ROOT_PYPROJECT,
    is_distribution,
    load_toml,
    tracked_pyprojects,
)
from packaging.version import InvalidVersion, Version
from version_bump import rewrite_version

if TYPE_CHECKING:
    from pathlib import Path


def rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def current_version() -> str:
    version = load_toml(ROOT_PYPROJECT).get("project", {}).get("version")
    if not isinstance(version, str) or not version:
        print("error: pyproject.toml: missing [project].version", file=sys.stderr)
        raise SystemExit(1)
    return version


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="the new version, e.g. 0.12.0.dev0")
    args = parser.parse_args()

    try:
        Version(args.version)
    except InvalidVersion as err:
        print(f"error: {args.version!r} is not a valid PEP 440 version: {err}", file=sys.stderr)
        return 1

    old = current_version()
    if old == args.version:
        print(f"error: already on version {old}", file=sys.stderr)
        return 1

    targets = [ROOT_PYPROJECT]
    targets += [path for path in tracked_pyprojects() if path != ROOT_PYPROJECT and is_distribution(load_toml(path))]

    # Confirm each file's own declaration is the version being moved, before writing
    # anything: a file can carry `old` in a pin or a comment while its own version is
    # already something else, and rewriting that would report success without moving it.
    undeclared = [path for path in targets if load_toml(path).get("project", {}).get("version") != old]
    if undeclared:
        for path in undeclared:
            print(f"error: {rel(path)}: [project].version is not {old}; nothing was changed", file=sys.stderr)
        return 1

    try:
        stale, changes = rewrite_version(targets, old, args.version)
    except OSError as err:
        print(f"error: {err}; any files already written were restored", file=sys.stderr)
        return 1
    if stale:
        for path in stale:
            print(
                f"error: {rel(path)} does not carry version {old}; nothing was changed",
                file=sys.stderr,
            )
        return 1

    # A file can contain the old version somewhere other than its own `[project].version`
    # -- a stale pin, say -- so confirm the declaration itself actually moved.
    undeclared = [path for path in targets if load_toml(path).get("project", {}).get("version") != args.version]
    if undeclared:
        for path in undeclared:
            print(
                f"error: {rel(path)}: [project].version is still not {args.version}",
                file=sys.stderr,
            )
        return 1

    for path, count in changes:
        print(f"  {rel(path)} ({count})")
    print(f"{old} -> {args.version} in {len(changes)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
