"""Run Rust doc tests via the unified test crate.

This test invokes `cargo test` on the unified Rust crate that contains all
Rust documentation examples as native #[test] functions. This ensures the
pytest test suite covers Rust doc examples without creating temporary Cargo
projects per test.

The unified crate is generated by: scripts/docs/generate_doc_tests.py
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

RUST_CRATE_DIR = Path(__file__).parent / "rust_crate"


@pytest.mark.slow
def test_rust_doc_examples() -> None:
    """Run all Rust doc examples via the unified test crate."""
    if not (RUST_CRATE_DIR / "Cargo.toml").exists():
        pytest.skip("Unified Rust test crate not found")

    result = subprocess.run(
        ["cargo", "test"],
        cwd=RUST_CRATE_DIR,
        capture_output=True,
        text=True,
        timeout=600,
        check=False,
    )

    if result.returncode != 0:
        # Extract just the test result lines and failures for readable output
        lines = result.stdout.splitlines()
        summary = [ln for ln in lines if "test result" in ln or "FAILED" in ln]
        stderr_tail = "\n".join(result.stderr.splitlines()[-20:]) if result.stderr else ""
        msg = "Rust doc tests failed:\n" + "\n".join(summary)
        if stderr_tail:
            msg += "\n\nstderr (last 20 lines):\n" + stderr_tail
        pytest.fail(msg)
